/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppSchemasDatasourceDataSourceCreate,
  AppSchemasDatasourceDataSourceUpdate,
  DataSourceRead,
  FactoryCreate,
  FactoryRead,
  FactoryUpdate,
  FactoryWithDataSources,
  HTTPValidationError
} from '../../model';

import { customInstance } from '../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get all factories for the current user's organization.

RBAC:
- OWNER/ADMIN: See all active factories in organization.
- MANAGER: Only see factories where they have assigned lines.
 * @summary List Factories
 */
export const listFactoriesApiV1FactoriesGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<FactoryRead[]>(
      {url: `/api/v1/factories`, method: 'GET', signal
    },
      options);
    }
  



export const getListFactoriesApiV1FactoriesGetQueryKey = () => {
    return [
    `/api/v1/factories`
    ] as const;
    }

    
export const getListFactoriesApiV1FactoriesGetQueryOptions = <TData = Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFactoriesApiV1FactoriesGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>> = ({ signal }) => listFactoriesApiV1FactoriesGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFactoriesApiV1FactoriesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>>
export type ListFactoriesApiV1FactoriesGetQueryError = unknown


export function useListFactoriesApiV1FactoriesGet<TData = Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>,
          TError,
          Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFactoriesApiV1FactoriesGet<TData = Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>,
          TError,
          Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFactoriesApiV1FactoriesGet<TData = Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Factories
 */

export function useListFactoriesApiV1FactoriesGet<TData = Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFactoriesApiV1FactoriesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFactoriesApiV1FactoriesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create a new factory with quota enforcement.
 * @summary Create Factory
 */
export const createFactoryApiV1FactoriesPost = (
    factoryCreate: FactoryCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<FactoryRead>(
      {url: `/api/v1/factories`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: factoryCreate, signal
    },
      options);
    }
  


export const getCreateFactoryApiV1FactoriesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFactoryApiV1FactoriesPost>>, TError,{data: FactoryCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createFactoryApiV1FactoriesPost>>, TError,{data: FactoryCreate}, TContext> => {

const mutationKey = ['createFactoryApiV1FactoriesPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFactoryApiV1FactoriesPost>>, {data: FactoryCreate}> = (props) => {
          const {data} = props ?? {};

          return  createFactoryApiV1FactoriesPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateFactoryApiV1FactoriesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createFactoryApiV1FactoriesPost>>>
    export type CreateFactoryApiV1FactoriesPostMutationBody = FactoryCreate
    export type CreateFactoryApiV1FactoriesPostMutationError = HTTPValidationError

    /**
 * @summary Create Factory
 */
export const useCreateFactoryApiV1FactoriesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFactoryApiV1FactoriesPost>>, TError,{data: FactoryCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFactoryApiV1FactoriesPost>>,
        TError,
        {data: FactoryCreate},
        TContext
      > => {

      const mutationOptions = getCreateFactoryApiV1FactoriesPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get a specific factory with its production lines.

RBAC Filtering:
- SYSTEM_ADMIN/OWNER: See all lines
- MANAGER: Only see lines assigned via UserScope
 * @summary Get Factory
 */
export const getFactoryApiV1FactoriesFactoryIdGet = (
    factoryId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<FactoryWithDataSources>(
      {url: `/api/v1/factories/${factoryId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetFactoryApiV1FactoriesFactoryIdGetQueryKey = (factoryId?: string,) => {
    return [
    `/api/v1/factories/${factoryId}`
    ] as const;
    }

    
export const getGetFactoryApiV1FactoriesFactoryIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>, TError = HTTPValidationError>(factoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFactoryApiV1FactoriesFactoryIdGetQueryKey(factoryId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>> = ({ signal }) => getFactoryApiV1FactoriesFactoryIdGet(factoryId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(factoryId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFactoryApiV1FactoriesFactoryIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>>
export type GetFactoryApiV1FactoriesFactoryIdGetQueryError = HTTPValidationError


export function useGetFactoryApiV1FactoriesFactoryIdGet<TData = Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>, TError = HTTPValidationError>(
 factoryId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>,
          TError,
          Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFactoryApiV1FactoriesFactoryIdGet<TData = Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>, TError = HTTPValidationError>(
 factoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>,
          TError,
          Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFactoryApiV1FactoriesFactoryIdGet<TData = Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>, TError = HTTPValidationError>(
 factoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Factory
 */

export function useGetFactoryApiV1FactoriesFactoryIdGet<TData = Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>, TError = HTTPValidationError>(
 factoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFactoryApiV1FactoriesFactoryIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFactoryApiV1FactoriesFactoryIdGetQueryOptions(factoryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update an existing factory.
 * @summary Update Factory
 */
export const updateFactoryApiV1FactoriesFactoryIdPatch = (
    factoryId: string,
    factoryUpdate: FactoryUpdate,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<FactoryRead>(
      {url: `/api/v1/factories/${factoryId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: factoryUpdate
    },
      options);
    }
  


export const getUpdateFactoryApiV1FactoriesFactoryIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFactoryApiV1FactoriesFactoryIdPatch>>, TError,{factoryId: string;data: FactoryUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateFactoryApiV1FactoriesFactoryIdPatch>>, TError,{factoryId: string;data: FactoryUpdate}, TContext> => {

const mutationKey = ['updateFactoryApiV1FactoriesFactoryIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFactoryApiV1FactoriesFactoryIdPatch>>, {factoryId: string;data: FactoryUpdate}> = (props) => {
          const {factoryId,data} = props ?? {};

          return  updateFactoryApiV1FactoriesFactoryIdPatch(factoryId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateFactoryApiV1FactoriesFactoryIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateFactoryApiV1FactoriesFactoryIdPatch>>>
    export type UpdateFactoryApiV1FactoriesFactoryIdPatchMutationBody = FactoryUpdate
    export type UpdateFactoryApiV1FactoriesFactoryIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Factory
 */
export const useUpdateFactoryApiV1FactoriesFactoryIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFactoryApiV1FactoriesFactoryIdPatch>>, TError,{factoryId: string;data: FactoryUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFactoryApiV1FactoriesFactoryIdPatch>>,
        TError,
        {factoryId: string;data: FactoryUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateFactoryApiV1FactoriesFactoryIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Soft-delete a factory.
 * @summary Delete Factory
 */
export const deleteFactoryApiV1FactoriesFactoryIdDelete = (
    factoryId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/factories/${factoryId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteFactoryApiV1FactoriesFactoryIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFactoryApiV1FactoriesFactoryIdDelete>>, TError,{factoryId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteFactoryApiV1FactoriesFactoryIdDelete>>, TError,{factoryId: string}, TContext> => {

const mutationKey = ['deleteFactoryApiV1FactoriesFactoryIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFactoryApiV1FactoriesFactoryIdDelete>>, {factoryId: string}> = (props) => {
          const {factoryId} = props ?? {};

          return  deleteFactoryApiV1FactoriesFactoryIdDelete(factoryId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteFactoryApiV1FactoriesFactoryIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFactoryApiV1FactoriesFactoryIdDelete>>>
    
    export type DeleteFactoryApiV1FactoriesFactoryIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Factory
 */
export const useDeleteFactoryApiV1FactoriesFactoryIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFactoryApiV1FactoriesFactoryIdDelete>>, TError,{factoryId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFactoryApiV1FactoriesFactoryIdDelete>>,
        TError,
        {factoryId: string},
        TContext
      > => {

      const mutationOptions = getDeleteFactoryApiV1FactoriesFactoryIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get data sources for a factory.

RBAC Filtering:
- SYSTEM_ADMIN/OWNER: See all data sources in the factory
- MANAGER: Only see data sources assigned via UserScope
- ANALYST/VIEWER: See all data sources (read-only)
 * @summary List Data Sources
 */
export const listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet = (
    factoryId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DataSourceRead[]>(
      {url: `/api/v1/factories/${factoryId}/data-sources`, method: 'GET', signal
    },
      options);
    }
  



export const getListDataSourcesApiV1FactoriesFactoryIdDataSourcesGetQueryKey = (factoryId?: string,) => {
    return [
    `/api/v1/factories/${factoryId}/data-sources`
    ] as const;
    }

    
export const getListDataSourcesApiV1FactoriesFactoryIdDataSourcesGetQueryOptions = <TData = Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>, TError = HTTPValidationError>(factoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDataSourcesApiV1FactoriesFactoryIdDataSourcesGetQueryKey(factoryId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>> = ({ signal }) => listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet(factoryId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(factoryId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDataSourcesApiV1FactoriesFactoryIdDataSourcesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>>
export type ListDataSourcesApiV1FactoriesFactoryIdDataSourcesGetQueryError = HTTPValidationError


export function useListDataSourcesApiV1FactoriesFactoryIdDataSourcesGet<TData = Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>, TError = HTTPValidationError>(
 factoryId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>,
          TError,
          Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDataSourcesApiV1FactoriesFactoryIdDataSourcesGet<TData = Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>, TError = HTTPValidationError>(
 factoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>,
          TError,
          Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDataSourcesApiV1FactoriesFactoryIdDataSourcesGet<TData = Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>, TError = HTTPValidationError>(
 factoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Data Sources
 */

export function useListDataSourcesApiV1FactoriesFactoryIdDataSourcesGet<TData = Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>, TError = HTTPValidationError>(
 factoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSourcesApiV1FactoriesFactoryIdDataSourcesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDataSourcesApiV1FactoriesFactoryIdDataSourcesGetQueryOptions(factoryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create a new data source with quota enforcement.
 * @summary Create Data Source
 */
export const createDataSourceApiV1FactoriesFactoryIdDataSourcesPost = (
    factoryId: string,
    appSchemasDatasourceDataSourceCreate: AppSchemasDatasourceDataSourceCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DataSourceRead>(
      {url: `/api/v1/factories/${factoryId}/data-sources`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: appSchemasDatasourceDataSourceCreate, signal
    },
      options);
    }
  


export const getCreateDataSourceApiV1FactoriesFactoryIdDataSourcesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDataSourceApiV1FactoriesFactoryIdDataSourcesPost>>, TError,{factoryId: string;data: AppSchemasDatasourceDataSourceCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createDataSourceApiV1FactoriesFactoryIdDataSourcesPost>>, TError,{factoryId: string;data: AppSchemasDatasourceDataSourceCreate}, TContext> => {

const mutationKey = ['createDataSourceApiV1FactoriesFactoryIdDataSourcesPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDataSourceApiV1FactoriesFactoryIdDataSourcesPost>>, {factoryId: string;data: AppSchemasDatasourceDataSourceCreate}> = (props) => {
          const {factoryId,data} = props ?? {};

          return  createDataSourceApiV1FactoriesFactoryIdDataSourcesPost(factoryId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDataSourceApiV1FactoriesFactoryIdDataSourcesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createDataSourceApiV1FactoriesFactoryIdDataSourcesPost>>>
    export type CreateDataSourceApiV1FactoriesFactoryIdDataSourcesPostMutationBody = AppSchemasDatasourceDataSourceCreate
    export type CreateDataSourceApiV1FactoriesFactoryIdDataSourcesPostMutationError = HTTPValidationError

    /**
 * @summary Create Data Source
 */
export const useCreateDataSourceApiV1FactoriesFactoryIdDataSourcesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDataSourceApiV1FactoriesFactoryIdDataSourcesPost>>, TError,{factoryId: string;data: AppSchemasDatasourceDataSourceCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDataSourceApiV1FactoriesFactoryIdDataSourcesPost>>,
        TError,
        {factoryId: string;data: AppSchemasDatasourceDataSourceCreate},
        TContext
      > => {

      const mutationOptions = getCreateDataSourceApiV1FactoriesFactoryIdDataSourcesPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get a specific data source.
Path: /factories/data-sources/{ds_id}
 * @summary Get Data Source
 */
export const getDataSourceApiV1FactoriesDataSourcesDsIdGet = (
    dsId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DataSourceRead>(
      {url: `/api/v1/factories/data-sources/${dsId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetDataSourceApiV1FactoriesDataSourcesDsIdGetQueryKey = (dsId?: string,) => {
    return [
    `/api/v1/factories/data-sources/${dsId}`
    ] as const;
    }

    
export const getGetDataSourceApiV1FactoriesDataSourcesDsIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>, TError = HTTPValidationError>(dsId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDataSourceApiV1FactoriesDataSourcesDsIdGetQueryKey(dsId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>> = ({ signal }) => getDataSourceApiV1FactoriesDataSourcesDsIdGet(dsId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(dsId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDataSourceApiV1FactoriesDataSourcesDsIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>>
export type GetDataSourceApiV1FactoriesDataSourcesDsIdGetQueryError = HTTPValidationError


export function useGetDataSourceApiV1FactoriesDataSourcesDsIdGet<TData = Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>, TError = HTTPValidationError>(
 dsId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>,
          TError,
          Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDataSourceApiV1FactoriesDataSourcesDsIdGet<TData = Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>, TError = HTTPValidationError>(
 dsId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>,
          TError,
          Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDataSourceApiV1FactoriesDataSourcesDsIdGet<TData = Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>, TError = HTTPValidationError>(
 dsId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Data Source
 */

export function useGetDataSourceApiV1FactoriesDataSourcesDsIdGet<TData = Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>, TError = HTTPValidationError>(
 dsId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDataSourceApiV1FactoriesDataSourcesDsIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDataSourceApiV1FactoriesDataSourcesDsIdGetQueryOptions(dsId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update a data source.
Path: /factories/data-sources/{ds_id}
 * @summary Update Data Source
 */
export const updateDataSourceApiV1FactoriesDataSourcesDsIdPatch = (
    dsId: string,
    appSchemasDatasourceDataSourceUpdate: AppSchemasDatasourceDataSourceUpdate,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DataSourceRead>(
      {url: `/api/v1/factories/data-sources/${dsId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: appSchemasDatasourceDataSourceUpdate
    },
      options);
    }
  


export const getUpdateDataSourceApiV1FactoriesDataSourcesDsIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDataSourceApiV1FactoriesDataSourcesDsIdPatch>>, TError,{dsId: string;data: AppSchemasDatasourceDataSourceUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDataSourceApiV1FactoriesDataSourcesDsIdPatch>>, TError,{dsId: string;data: AppSchemasDatasourceDataSourceUpdate}, TContext> => {

const mutationKey = ['updateDataSourceApiV1FactoriesDataSourcesDsIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDataSourceApiV1FactoriesDataSourcesDsIdPatch>>, {dsId: string;data: AppSchemasDatasourceDataSourceUpdate}> = (props) => {
          const {dsId,data} = props ?? {};

          return  updateDataSourceApiV1FactoriesDataSourcesDsIdPatch(dsId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateDataSourceApiV1FactoriesDataSourcesDsIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateDataSourceApiV1FactoriesDataSourcesDsIdPatch>>>
    export type UpdateDataSourceApiV1FactoriesDataSourcesDsIdPatchMutationBody = AppSchemasDatasourceDataSourceUpdate
    export type UpdateDataSourceApiV1FactoriesDataSourcesDsIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Data Source
 */
export const useUpdateDataSourceApiV1FactoriesDataSourcesDsIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDataSourceApiV1FactoriesDataSourcesDsIdPatch>>, TError,{dsId: string;data: AppSchemasDatasourceDataSourceUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDataSourceApiV1FactoriesDataSourcesDsIdPatch>>,
        TError,
        {dsId: string;data: AppSchemasDatasourceDataSourceUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateDataSourceApiV1FactoriesDataSourcesDsIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Soft-delete a data source.
Path: /factories/data-sources/{ds_id}
 * @summary Delete Data Source
 */
export const deleteDataSourceApiV1FactoriesDataSourcesDsIdDelete = (
    dsId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/factories/data-sources/${dsId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteDataSourceApiV1FactoriesDataSourcesDsIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDataSourceApiV1FactoriesDataSourcesDsIdDelete>>, TError,{dsId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDataSourceApiV1FactoriesDataSourcesDsIdDelete>>, TError,{dsId: string}, TContext> => {

const mutationKey = ['deleteDataSourceApiV1FactoriesDataSourcesDsIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDataSourceApiV1FactoriesDataSourcesDsIdDelete>>, {dsId: string}> = (props) => {
          const {dsId} = props ?? {};

          return  deleteDataSourceApiV1FactoriesDataSourcesDsIdDelete(dsId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDataSourceApiV1FactoriesDataSourcesDsIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDataSourceApiV1FactoriesDataSourcesDsIdDelete>>>
    
    export type DeleteDataSourceApiV1FactoriesDataSourcesDsIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Data Source
 */
export const useDeleteDataSourceApiV1FactoriesDataSourcesDsIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDataSourceApiV1FactoriesDataSourcesDsIdDelete>>, TError,{dsId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDataSourceApiV1FactoriesDataSourcesDsIdDelete>>,
        TError,
        {dsId: string},
        TContext
      > => {

      const mutationOptions = getDeleteDataSourceApiV1FactoriesDataSourcesDsIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    