/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  WaitlistCreate,
  WaitlistResponse
} from '../../model';

import { customInstance } from '../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Join the waitlist.
Returns the created entry with a unique referral code.
 * @summary Join Waitlist
 */
export const joinWaitlistApiV1WaitlistPost = (
    waitlistCreate: WaitlistCreate,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<WaitlistResponse>(
      {url: `/api/v1/waitlist/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: waitlistCreate, signal
    },
      options);
    }
  


export const getJoinWaitlistApiV1WaitlistPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof joinWaitlistApiV1WaitlistPost>>, TError,{data: WaitlistCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof joinWaitlistApiV1WaitlistPost>>, TError,{data: WaitlistCreate}, TContext> => {

const mutationKey = ['joinWaitlistApiV1WaitlistPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof joinWaitlistApiV1WaitlistPost>>, {data: WaitlistCreate}> = (props) => {
          const {data} = props ?? {};

          return  joinWaitlistApiV1WaitlistPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type JoinWaitlistApiV1WaitlistPostMutationResult = NonNullable<Awaited<ReturnType<typeof joinWaitlistApiV1WaitlistPost>>>
    export type JoinWaitlistApiV1WaitlistPostMutationBody = WaitlistCreate
    export type JoinWaitlistApiV1WaitlistPostMutationError = HTTPValidationError

    /**
 * @summary Join Waitlist
 */
export const useJoinWaitlistApiV1WaitlistPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof joinWaitlistApiV1WaitlistPost>>, TError,{data: WaitlistCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof joinWaitlistApiV1WaitlistPost>>,
        TError,
        {data: WaitlistCreate},
        TContext
      > => {

      const mutationOptions = getJoinWaitlistApiV1WaitlistPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    