import React, { useMemo } from 'react';
import {
    AreaChart,
    Area,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    ResponsiveContainer,
    Legend
} from 'recharts';
import type { SmartWidgetProps } from '../config';
import { z } from 'zod';
import { ProductionChartDataSchema } from '../registry';
import { useFactoryFormat } from '@/hooks/useFactoryFormat';

// Input type inferred from Zod Schema
type DataProps = z.infer<typeof ProductionChartDataSchema>;
// Explicitly define settings type or use 'any' if lazy for now. 
// Ideally we infer from ProductionChartSettingsSchema but we need to export it first.
// For now, we will use a loose type to fix the error.
interface ProductionSettings {
    showLegend?: boolean;
    yAxisMax?: number;
    customTitle?: string;
    refreshRate?: number;
}

const ProductionChart: React.FC<SmartWidgetProps<DataProps, ProductionSettings>> = ({
    data,
    settings,
    w: _w,
    h: _h
}) => {
    // 1. Settings Extraction
    const showLegend = settings?.showLegend !== false;
    const yAxisMax = settings?.yAxisMax || 0;
    const { formatDate } = useFactoryFormat();

    // 2. Data Preparation
    // Handle new API response shape: { data_points: [...], line_filter: "..." }
    const chartData = useMemo(() => {
        // API returns object with data_points array
        if (data && 'data_points' in data && Array.isArray(data.data_points)) {
            return data.data_points;
        }
        // Fallback for legacy array format
        return Array.isArray(data) ? data : [];
    }, [data]);


    // MOCK DATA NOTICE: The 'data' passed here is validated against ProductionChartDataSchema
    // but may still be generated by the mock provider if in development mode.

    return (
        <ResponsiveContainer width="100%" height="100%">
            <AreaChart
                data={chartData}
                margin={{ top: 5, right: 5, left: -20, bottom: 0 }}
            >
                <defs>
                    <linearGradient id="colorActual" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.3} />
                        <stop offset="95%" stopColor="#3b82f6" stopOpacity={0} />
                    </linearGradient>
                    <linearGradient id="colorPlanned" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#94a3b8" stopOpacity={0.3} />
                        <stop offset="95%" stopColor="#94a3b8" stopOpacity={0} />
                    </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                <XAxis
                    dataKey="day"
                    tick={{ fontSize: 10, fill: '#64748b' }}
                    axisLine={false}
                    tickLine={false}
                    tickFormatter={(val) => formatDate(val)}
                />
                <YAxis
                    tick={{ fontSize: 10, fill: '#64748b' }}
                    axisLine={false}
                    tickLine={false}
                    domain={[0, yAxisMax || 'auto']}
                />
                <Tooltip
                    contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                    labelStyle={{ color: '#64748b', fontSize: '12px' }}
                    labelFormatter={(label) => formatDate(label)}
                />
                {showLegend && (
                    <Legend
                        wrapperStyle={{ fontSize: '10px', paddingTop: '10px' }}
                        iconType="circle"
                    />
                )}
                <Area
                    type="monotone"
                    dataKey="target"
                    name="Planned"
                    stroke="#94a3b8"
                    strokeWidth={2}
                    strokeDasharray="4 4"
                    fill="url(#colorPlanned)"
                />
                <Area
                    type="monotone"
                    dataKey="actual"
                    name="Actual Output"
                    stroke="#3b82f6"
                    strokeWidth={2}
                    fill="url(#colorActual)"
                />

            </AreaChart>
        </ResponsiveContainer>
    );
};

export default ProductionChart;
