/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type of AI agent that made the decision.
 */
export type AgentType = typeof AgentType[keyof typeof AgentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AgentType = {
  schema_inference: 'schema_inference',
  code_generation: 'code_generation',
} as const;
