/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { AppApiV1EndpointsDatasourceDataSourceUpdateName } from './appApiV1EndpointsDatasourceDataSourceUpdateName';
import type { AppApiV1EndpointsDatasourceDataSourceUpdateCode } from './appApiV1EndpointsDatasourceDataSourceUpdateCode';
import type { AppApiV1EndpointsDatasourceDataSourceUpdateSpecialty } from './appApiV1EndpointsDatasourceDataSourceUpdateSpecialty';
import type { AppApiV1EndpointsDatasourceDataSourceUpdateTargetOperators } from './appApiV1EndpointsDatasourceDataSourceUpdateTargetOperators';
import type { AppApiV1EndpointsDatasourceDataSourceUpdateTargetEfficiencyPct } from './appApiV1EndpointsDatasourceDataSourceUpdateTargetEfficiencyPct';
import type { AppApiV1EndpointsDatasourceDataSourceUpdateIsActive } from './appApiV1EndpointsDatasourceDataSourceUpdateIsActive';
import type { AppApiV1EndpointsDatasourceDataSourceUpdateSettings } from './appApiV1EndpointsDatasourceDataSourceUpdateSettings';
import type { AppApiV1EndpointsDatasourceDataSourceUpdateTimeColumn } from './appApiV1EndpointsDatasourceDataSourceUpdateTimeColumn';
import type { AppApiV1EndpointsDatasourceDataSourceUpdateTimeFormat } from './appApiV1EndpointsDatasourceDataSourceUpdateTimeFormat';
import type { AppApiV1EndpointsDatasourceDataSourceUpdateDescription } from './appApiV1EndpointsDatasourceDataSourceUpdateDescription';
import type { AppApiV1EndpointsDatasourceDataSourceUpdateSourceName } from './appApiV1EndpointsDatasourceDataSourceUpdateSourceName';

/**
 * Schema for updating DataSource configuration.
 */
export interface AppApiV1EndpointsDatasourceDataSourceUpdate {
  name?: AppApiV1EndpointsDatasourceDataSourceUpdateName;
  code?: AppApiV1EndpointsDatasourceDataSourceUpdateCode;
  specialty?: AppApiV1EndpointsDatasourceDataSourceUpdateSpecialty;
  target_operators?: AppApiV1EndpointsDatasourceDataSourceUpdateTargetOperators;
  target_efficiency_pct?: AppApiV1EndpointsDatasourceDataSourceUpdateTargetEfficiencyPct;
  is_active?: AppApiV1EndpointsDatasourceDataSourceUpdateIsActive;
  settings?: AppApiV1EndpointsDatasourceDataSourceUpdateSettings;
  time_column?: AppApiV1EndpointsDatasourceDataSourceUpdateTimeColumn;
  time_format?: AppApiV1EndpointsDatasourceDataSourceUpdateTimeFormat;
  description?: AppApiV1EndpointsDatasourceDataSourceUpdateDescription;
  source_name?: AppApiV1EndpointsDatasourceDataSourceUpdateSourceName;
}
