/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { AppSchemasDatasourceDataSourceCreateCode } from './appSchemasDatasourceDataSourceCreateCode';
import type { AppSchemasDatasourceDataSourceCreateSpecialty } from './appSchemasDatasourceDataSourceCreateSpecialty';
import type { AppSchemasDatasourceDataSourceCreateTargetOperators } from './appSchemasDatasourceDataSourceCreateTargetOperators';
import type { AppSchemasDatasourceDataSourceCreateTargetEfficiencyPct } from './appSchemasDatasourceDataSourceCreateTargetEfficiencyPct';
import type { AppSchemasDatasourceDataSourceCreateSettings } from './appSchemasDatasourceDataSourceCreateSettings';
import type { AppSchemasDatasourceDataSourceCreateSourceName } from './appSchemasDatasourceDataSourceCreateSourceName';
import type { AppSchemasDatasourceDataSourceCreateDescription } from './appSchemasDatasourceDataSourceCreateDescription';
import type { AppSchemasDatasourceDataSourceCreateTimeColumn } from './appSchemasDatasourceDataSourceCreateTimeColumn';
import type { AppSchemasDatasourceDataSourceCreateTimeFormat } from './appSchemasDatasourceDataSourceCreateTimeFormat';

/**
 * Schema for creating a data source.
 */
export interface AppSchemasDatasourceDataSourceCreate {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  code?: AppSchemasDatasourceDataSourceCreateCode;
  specialty?: AppSchemasDatasourceDataSourceCreateSpecialty;
  target_operators?: AppSchemasDatasourceDataSourceCreateTargetOperators;
  target_efficiency_pct?: AppSchemasDatasourceDataSourceCreateTargetEfficiencyPct;
  /** ID of the factory this data source belongs to */
  factory_id: string;
  settings?: AppSchemasDatasourceDataSourceCreateSettings;
  source_name?: AppSchemasDatasourceDataSourceCreateSourceName;
  description?: AppSchemasDatasourceDataSourceCreateDescription;
  time_column?: AppSchemasDatasourceDataSourceCreateTimeColumn;
  time_format?: AppSchemasDatasourceDataSourceCreateTimeFormat;
}
