/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Available canonical field for UI dropdown.
 */
export interface AvailableField {
  /** Canonical field name (e.g., 'actual_qty') */
  field: string;
  /** Human-readable description */
  description: string;
}
