/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { ColumnMappingConfirmationTargetField } from './columnMappingConfirmationTargetField';

/**
 * User's confirmed mapping for a single column.

Used when submitting final mappings after review.
 */
export interface ColumnMappingConfirmation {
  /** Original column name from file */
  source_column: string;
  /** Canonical field to map to (None if ignored) */
  target_field?: ColumnMappingConfirmationTargetField;
  /** True if column should be skipped */
  ignored?: boolean;
  /** True if user changed the AI suggestion */
  user_corrected?: boolean;
}
