/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { ColumnMappingResultTargetField } from './columnMappingResultTargetField';
import type { MatchTier } from './matchTier';
import type { ColumnMappingResultFuzzyScore } from './columnMappingResultFuzzyScore';
import type { ColumnMappingResultReasoning } from './columnMappingResultReasoning';

/**
 * API response for a single column mapping result.

Represents the engine's best guess for mapping a source column
to a canonical target field, with confidence scoring.
 */
export interface ColumnMappingResult {
  /** Original column name from uploaded file */
  source_column: string;
  /** Canonical field name (e.g., 'actual_qty', 'production_date') */
  target_field?: ColumnMappingResultTargetField;
  /**
   * Confidence score (0.0 to 1.0)
   * @minimum 0
   * @maximum 1
   */
  confidence: number;
  /** Matching tier used: 'hash', 'fuzzy', 'llm', 'manual', 'unmatched' */
  tier: MatchTier;
  /** RapidFuzz similarity score (0-100) if tier='fuzzy' */
  fuzzy_score?: ColumnMappingResultFuzzyScore;
  /** Explanation from matching engine (especially for LLM tier) */
  reasoning?: ColumnMappingResultReasoning;
  /** Sample values from this column (first 5 non-null) */
  sample_data?: unknown[];
  /** True if confidence is medium (0.6-0.9) */
  needs_review?: boolean;
  /** True if column should be skipped during import */
  ignored?: boolean;
  /** Status: 'auto_mapped', 'needs_review', 'needs_attention', 'ignored' */
  status: string;
}
