/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Single point for Complexity Impact scatter plot.
 */
export interface ComplexityPoint {
  /** Style UUID */
  style_id: string;
  /**
   * Standard Allowed Minute (Difficulty)
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   */
  sam: string;
  /**
   * Performance efficiency on this style
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   */
  efficiency_pct: string;
  /** Style code text for tooltip */
  style_code: string;
}
