/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response after confirming mapping.
 */
export interface ConfirmMappingResponse {
  /** UUID of created/updated SchemaMapping */
  schema_mapping_id: string;
  /** UUID of associated DataSource */
  data_source_id: string;
  /** Number of new aliases learned from corrections */
  learned_aliases: number;
  /** Human-readable success message */
  message: string;
}
