/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardCreateDescription } from './dashboardCreateDescription';
import type { DashboardCreateDataSourceId } from './dashboardCreateDataSourceId';
import type { DashboardCreateWidgetConfig } from './dashboardCreateWidgetConfig';
import type { DashboardCreateLayoutConfig } from './dashboardCreateLayoutConfig';

/**
 * Schema for creating a new dashboard.
 */
export interface DashboardCreate {
  /**
   * Dashboard name
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  /** Dashboard description */
  description?: DashboardCreateDescription;
  /** UUID of the linked ExcelUpload */
  data_source_id?: DashboardCreateDataSourceId;
  /** Widget configuration */
  widget_config?: DashboardCreateWidgetConfig;
  /** Layout configuration */
  layout_config?: DashboardCreateLayoutConfig;
}
