/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardResponseDescription } from './dashboardResponseDescription';
import type { DashboardResponseDataSourceId } from './dashboardResponseDataSourceId';
import type { DashboardResponseWidgetConfig } from './dashboardResponseWidgetConfig';
import type { DashboardResponseLayoutConfig } from './dashboardResponseLayoutConfig';

/**
 * Basic dashboard response schema.
 */
export interface DashboardResponse {
  id: string;
  user_id: string;
  name: string;
  description?: DashboardResponseDescription;
  data_source_id?: DashboardResponseDataSourceId;
  widget_config?: DashboardResponseWidgetConfig;
  layout_config?: DashboardResponseLayoutConfig;
  created_at: string;
  updated_at: string;
}
