/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardDetailResponseDescription } from './dashboardDetailResponseDescription';
import type { DashboardDetailResponseDataSourceId } from './dashboardDetailResponseDataSourceId';
import type { DashboardDetailResponseWidgetConfig } from './dashboardDetailResponseWidgetConfig';
import type { DashboardDetailResponseLayoutConfig } from './dashboardDetailResponseLayoutConfig';
import type { DashboardDetailResponseWidgetData } from './dashboardDetailResponseWidgetData';

/**
 * Detailed dashboard response with widget data.
 */
export interface DashboardDetailResponse {
  id: string;
  user_id: string;
  name: string;
  description?: DashboardDetailResponseDescription;
  data_source_id?: DashboardDetailResponseDataSourceId;
  widget_config?: DashboardDetailResponseWidgetConfig;
  layout_config?: DashboardDetailResponseLayoutConfig;
  created_at: string;
  updated_at: string;
  /** Actual widget data fetched from data source */
  widget_data?: DashboardDetailResponseWidgetData;
}
