/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardUpdateName } from './dashboardUpdateName';
import type { DashboardUpdateDescription } from './dashboardUpdateDescription';
import type { DashboardUpdateDataSourceId } from './dashboardUpdateDataSourceId';
import type { DashboardUpdateWidgetConfig } from './dashboardUpdateWidgetConfig';
import type { DashboardUpdateLayoutConfig } from './dashboardUpdateLayoutConfig';

/**
 * Schema for updating an existing dashboard.
 */
export interface DashboardUpdate {
  name?: DashboardUpdateName;
  description?: DashboardUpdateDescription;
  data_source_id?: DashboardUpdateDataSourceId;
  widget_config?: DashboardUpdateWidgetConfig;
  layout_config?: DashboardUpdateLayoutConfig;
}
