/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { DataSourceResponseDescription } from './dataSourceResponseDescription';
import type { DataSourceResponseTimeColumn } from './dataSourceResponseTimeColumn';
import type { DataSourceResponseTimeFormat } from './dataSourceResponseTimeFormat';
import type { SchemaMappingResponse } from './schemaMappingResponse';

export interface DataSourceResponse {
  id: string;
  production_line_id: string;
  source_name: string;
  description: DataSourceResponseDescription;
  time_column?: DataSourceResponseTimeColumn;
  time_format?: DataSourceResponseTimeFormat;
  is_active: boolean;
  schema_mappings?: SchemaMappingResponse[];
  created_at: string;
}
