/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { DataSourceUpdateName } from './dataSourceUpdateName';
import type { DataSourceUpdateCode } from './dataSourceUpdateCode';
import type { DataSourceUpdateSpecialty } from './dataSourceUpdateSpecialty';
import type { DataSourceUpdateTargetOperators } from './dataSourceUpdateTargetOperators';
import type { DataSourceUpdateTargetEfficiencyPct } from './dataSourceUpdateTargetEfficiencyPct';
import type { DataSourceUpdateIsActive } from './dataSourceUpdateIsActive';
import type { DataSourceUpdateSettings } from './dataSourceUpdateSettings';
import type { DataSourceUpdateSourceName } from './dataSourceUpdateSourceName';
import type { DataSourceUpdateDescription } from './dataSourceUpdateDescription';
import type { DataSourceUpdateTimeColumn } from './dataSourceUpdateTimeColumn';
import type { DataSourceUpdateTimeFormat } from './dataSourceUpdateTimeFormat';

/**
 * Schema for updating a data source.
 */
export interface DataSourceUpdate {
  name?: DataSourceUpdateName;
  code?: DataSourceUpdateCode;
  specialty?: DataSourceUpdateSpecialty;
  target_operators?: DataSourceUpdateTargetOperators;
  target_efficiency_pct?: DataSourceUpdateTargetEfficiencyPct;
  is_active?: DataSourceUpdateIsActive;
  settings?: DataSourceUpdateSettings;
  source_name?: DataSourceUpdateSourceName;
  description?: DataSourceUpdateDescription;
  time_column?: DataSourceUpdateTimeColumn;
  time_format?: DataSourceUpdateTimeFormat;
}
