/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { DataSourceUpdateTimeColumn } from './dataSourceUpdateTimeColumn';
import type { DataSourceUpdateTimeFormat } from './dataSourceUpdateTimeFormat';
import type { DataSourceUpdateDescription } from './dataSourceUpdateDescription';
import type { DataSourceUpdateSourceName } from './dataSourceUpdateSourceName';

/**
 * Schema for updating DataSource configuration.
 */
export interface DataSourceUpdate {
  time_column?: DataSourceUpdateTimeColumn;
  time_format?: DataSourceUpdateTimeFormat;
  description?: DataSourceUpdateDescription;
  source_name?: DataSourceUpdateSourceName;
}
