/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { DataSourceCreateDescription } from './dataSourceCreateDescription';
import type { DataSourceCreateInitialMapping } from './dataSourceCreateInitialMapping';

export interface DataSourceCreate {
  production_line_id: string;
  source_name: string;
  description?: DataSourceCreateDescription;
  initial_mapping?: DataSourceCreateInitialMapping;
}
