/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { DataSourceSettingsShiftPattern } from './dataSourceSettingsShiftPattern';
import type { DataSourceSettingsNonWorkingDays } from './dataSourceSettingsNonWorkingDays';

/**
 * Settings specific to a data source.
Can be inherited from Factory defaults or overridden.
 */
export interface DataSourceSettings {
  /** If false, uses factory defaults */
  is_custom_schedule?: boolean;
  shift_pattern?: DataSourceSettingsShiftPattern;
  non_working_days?: DataSourceSettingsNonWorkingDays;
  [key: string]: unknown;
 }
