/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { DataSourceReadCode } from './dataSourceReadCode';
import type { DataSourceReadSpecialty } from './dataSourceReadSpecialty';
import type { DataSourceReadTargetOperators } from './dataSourceReadTargetOperators';
import type { DataSourceReadTargetEfficiencyPct } from './dataSourceReadTargetEfficiencyPct';
import type { DataSourceReadSupervisorId } from './dataSourceReadSupervisorId';
import type { DataSourceReadSourceName } from './dataSourceReadSourceName';
import type { DataSourceReadDescription } from './dataSourceReadDescription';
import type { DataSourceReadTimeColumn } from './dataSourceReadTimeColumn';
import type { DataSourceReadTimeFormat } from './dataSourceReadTimeFormat';
import type { DataSourceReadSettings } from './dataSourceReadSettings';
import type { DataSourceReadParentDataSourceId } from './dataSourceReadParentDataSourceId';
import type { DataSourceReadDateRangeStart } from './dataSourceReadDateRangeStart';
import type { DataSourceReadDateRangeEnd } from './dataSourceReadDateRangeEnd';

/**
 * Schema for reading a data source.
 */
export interface DataSourceRead {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  code?: DataSourceReadCode;
  specialty?: DataSourceReadSpecialty;
  target_operators?: DataSourceReadTargetOperators;
  target_efficiency_pct?: DataSourceReadTargetEfficiencyPct;
  id: string;
  factory_id: string;
  supervisor_id?: DataSourceReadSupervisorId;
  source_name?: DataSourceReadSourceName;
  description?: DataSourceReadDescription;
  time_column?: DataSourceReadTimeColumn;
  time_format?: DataSourceReadTimeFormat;
  settings?: DataSourceReadSettings;
  parent_data_source_id?: DataSourceReadParentDataSourceId;
  is_segment?: boolean;
  date_range_start?: DataSourceReadDateRangeStart;
  date_range_end?: DataSourceReadDateRangeEnd;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
