/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Single discrepancy alert.
 */
export interface DiscrepancyItem {
  /** Unique discrepancy UUID */
  id: string;
  /** Severity level: 'High', 'Medium', 'Low' */
  severity: string;
  /** Short title describing the data issue */
  issue_title: string;
  /** Detailed explanation of what triggered the discrepancy */
  issue_description: string;
  /** Name of the source file or record where the issue originated */
  source_file: string;
}
