/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Recurring downtime reason/keyword.
 */
export interface DowntimeReason {
  /** Keyword or reason extracted from notes */
  reason: string;
  /** Frequency count of this reason */
  count: number;
}
