/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { FactoryWithLinesCode } from './factoryWithLinesCode';
import type { FactoryWithLinesLocation } from './factoryWithLinesLocation';
import type { FactoryWithLinesCountry } from './factoryWithLinesCountry';
import type { FactoryWithLinesTimezone } from './factoryWithLinesTimezone';
import type { FactoryWithLinesCity } from './factoryWithLinesCity';
import type { FactoryWithLinesAddress } from './factoryWithLinesAddress';
import type { FactoryWithLinesTotalLines } from './factoryWithLinesTotalLines';
import type { FactoryWithLinesTotalWorkers } from './factoryWithLinesTotalWorkers';
import type { FactoryWithLinesDailyCapacityUnits } from './factoryWithLinesDailyCapacityUnits';
import type { FactoryWithLinesCertifications } from './factoryWithLinesCertifications';
import type { FactoryWithLinesSettings } from './factoryWithLinesSettings';
import type { ProductionLineRead } from './productionLineRead';

/**
 * Factory with production lines.
 */
export interface FactoryWithLines {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  code?: FactoryWithLinesCode;
  location?: FactoryWithLinesLocation;
  country?: FactoryWithLinesCountry;
  timezone?: FactoryWithLinesTimezone;
  id: string;
  organization_id: string;
  city?: FactoryWithLinesCity;
  address?: FactoryWithLinesAddress;
  total_lines?: FactoryWithLinesTotalLines;
  total_workers?: FactoryWithLinesTotalWorkers;
  daily_capacity_units?: FactoryWithLinesDailyCapacityUnits;
  certifications?: FactoryWithLinesCertifications;
  settings?: FactoryWithLinesSettings;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  production_lines?: ProductionLineRead[];
}
