/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { FactoryReadCode } from './factoryReadCode';
import type { FactoryReadLocation } from './factoryReadLocation';
import type { FactoryReadCountry } from './factoryReadCountry';
import type { FactoryReadTimezone } from './factoryReadTimezone';
import type { FactoryReadCity } from './factoryReadCity';
import type { FactoryReadAddress } from './factoryReadAddress';
import type { FactoryReadTotalLines } from './factoryReadTotalLines';
import type { FactoryReadTotalWorkers } from './factoryReadTotalWorkers';
import type { FactoryReadDailyCapacityUnits } from './factoryReadDailyCapacityUnits';
import type { FactoryReadCertifications } from './factoryReadCertifications';
import type { FactoryReadSettings } from './factoryReadSettings';

/**
 * Schema for reading a factory.
 */
export interface FactoryRead {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  code?: FactoryReadCode;
  location?: FactoryReadLocation;
  country?: FactoryReadCountry;
  timezone?: FactoryReadTimezone;
  id: string;
  organization_id: string;
  city?: FactoryReadCity;
  address?: FactoryReadAddress;
  total_lines?: FactoryReadTotalLines;
  total_workers?: FactoryReadTotalWorkers;
  daily_capacity_units?: FactoryReadDailyCapacityUnits;
  certifications?: FactoryReadCertifications;
  settings?: FactoryReadSettings;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
