/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { FactoryUpdateName } from './factoryUpdateName';
import type { FactoryUpdateLocation } from './factoryUpdateLocation';
import type { FactoryUpdateCountry } from './factoryUpdateCountry';
import type { FactoryUpdateTimezone } from './factoryUpdateTimezone';
import type { FactoryUpdateIsActive } from './factoryUpdateIsActive';
import type { FactoryUpdateSettings } from './factoryUpdateSettings';

/**
 * Schema for updating a factory.
 */
export interface FactoryUpdate {
  name?: FactoryUpdateName;
  location?: FactoryUpdateLocation;
  country?: FactoryUpdateCountry;
  timezone?: FactoryUpdateTimezone;
  is_active?: FactoryUpdateIsActive;
  settings?: FactoryUpdateSettings;
}
