/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { FactoryCreateLocation } from './factoryCreateLocation';
import type { FactoryCreateCountry } from './factoryCreateCountry';
import type { FactoryCreateTimezone } from './factoryCreateTimezone';
import type { FactoryCreateSettings } from './factoryCreateSettings';

/**
 * Schema for creating a factory.
 */
export interface FactoryCreate {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** @maxLength 50 */
  code: string;
  location?: FactoryCreateLocation;
  country?: FactoryCreateCountry;
  timezone?: FactoryCreateTimezone;
  settings?: FactoryCreateSettings;
}
