/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Widget layout position and size in grid.
 */
export interface LayoutItem {
  /** Unique identifier for the widget */
  widget_id: string;
  /**
   * X position in grid
   * @minimum 0
   */
  x: number;
  /**
   * Y position in grid
   * @minimum 0
   */
  y: number;
  /**
   * Width in grid units
   */
  w: number;
  /**
   * Height in grid units
   */
  h: number;
}
