/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

export type ListRunsApiV1ProductionRunsGetParams = {
order_id?: string | null;
line_id?: string | null;
date_from?: string | null;
date_to?: string | null;
skip?: number;
limit?: number;
sort_asc?: boolean;
};
