/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { AgentType } from './agentType';

export type ListAiDecisionsApiV1AiDecisionsGetParams = {
/**
 * Filter by data source ID
 */
data_source_id?: string | null;
/**
 * Filter by agent type
 */
agent_type?: AgentType | null;
/**
 * Filter by start date
 */
start_date?: string | null;
/**
 * Filter by end date
 */
end_date?: string | null;
/**
 * Number of results to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Number of results to skip
 * @minimum 0
 */
offset?: number;
};
