/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { UserInfo } from './userInfo';

/**
 * Login response with JWT token.
 */
export interface LoginResponse {
  access_token: string;
  token_type?: string;
  user: UserInfo;
}
