/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Column matching tier in waterfall engine.
 */
export type MatchTier = typeof MatchTier[keyof typeof MatchTier];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MatchTier = {
  hash: 'hash',
  fuzzy: 'fuzzy',
  llm: 'llm',
  manual: 'manual',
  unmatched: 'unmatched',
} as const;
