/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { MemberReadFullName } from './memberReadFullName';
import type { MemberReadAvatarUrl } from './memberReadAvatarUrl';
import type { MemberReadLastLogin } from './memberReadLastLogin';
import type { ScopeRead } from './scopeRead';

/**
 * Response schema for an organization member with their scopes.
 */
export interface MemberRead {
  id: string;
  email: string;
  full_name?: MemberReadFullName;
  avatar_url?: MemberReadAvatarUrl;
  role: string;
  is_active: boolean;
  last_login?: MemberReadLastLogin;
  scopes?: ScopeRead[];
}
