/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Order lifecycle status tracking.
 */
export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];


export const OrderStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  cutting: 'cutting',
  sewing: 'sewing',
  finishing: 'finishing',
  packing: 'packing',
  shipped: 'shipped',
  cancelled: 'cancelled',
} as const;
