/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { OrderReadSizeBreakdown } from './orderReadSizeBreakdown';
import type { OrderReadColor } from './orderReadColor';
import type { OrderReadOrderDate } from './orderReadOrderDate';
import type { OrderReadPlannedCutDate } from './orderReadPlannedCutDate';
import type { OrderReadPlannedSewDate } from './orderReadPlannedSewDate';
import type { OrderReadExFactoryDate } from './orderReadExFactoryDate';
import type { OrderStatus } from './orderStatus';
import type { PriorityLevel } from './priorityLevel';
import type { OrderReadNotes } from './orderReadNotes';

export interface OrderRead {
  /**
   * Purchase Order number from buyer (e.g., 'PO-2024-001')
   * @minLength 1
   * @maxLength 100
   */
  po_number: string;
  /**
   * Total order quantity in units
   */
  quantity: number;
  /** Quantity per size (e.g., {'S': 100, 'M': 200, 'L': 150}) */
  size_breakdown?: OrderReadSizeBreakdown;
  /**
   * Unit of measure (pcs, dozen, etc.)
   * @maxLength 20
   */
  uom?: string;
  /** Color/colorway (e.g., 'Navy Blue', 'Heather Grey') */
  color?: OrderReadColor;
  /** Date order was received */
  order_date?: OrderReadOrderDate;
  /** Planned Cut Date (PCD) - when fabric cutting should start */
  planned_cut_date?: OrderReadPlannedCutDate;
  /** Planned Sew Date (PSD) - when sewing should start */
  planned_sew_date?: OrderReadPlannedSewDate;
  /** Ex-Factory Date (EXD) - deadline for shipment from factory */
  ex_factory_date?: OrderReadExFactoryDate;
  /** Current order status in production lifecycle */
  status?: OrderStatus;
  /** Order priority level */
  priority?: PriorityLevel;
  /** Additional notes or special instructions */
  notes?: OrderReadNotes;
  id: string;
  style_id: string;
  qty_cut: number;
  qty_sewn: number;
  qty_packed: number;
  qty_shipped: number;
  created_at: string;
  updated_at: string;
}
