/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationReadCode } from './organizationReadCode';
import type { OrganizationReadPrimaryEmail } from './organizationReadPrimaryEmail';
import type { OrganizationReadPrimaryPhone } from './organizationReadPrimaryPhone';
import type { OrganizationReadSettings } from './organizationReadSettings';

/**
 * Schema for reading an organization.
 */
export interface OrganizationRead {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  code?: OrganizationReadCode;
  primary_email?: OrganizationReadPrimaryEmail;
  primary_phone?: OrganizationReadPrimaryPhone;
  id: string;
  subscription_tier: string;
  settings?: OrganizationReadSettings;
  created_at: string;
  updated_at: string;
}
