/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationUpdateName } from './organizationUpdateName';
import type { OrganizationUpdateCode } from './organizationUpdateCode';
import type { OrganizationUpdatePrimaryEmail } from './organizationUpdatePrimaryEmail';
import type { OrganizationUpdatePrimaryPhone } from './organizationUpdatePrimaryPhone';
import type { OrganizationUpdateSubscriptionTier } from './organizationUpdateSubscriptionTier';

/**
 * Schema for updating an organization.
 */
export interface OrganizationUpdate {
  name?: OrganizationUpdateName;
  code?: OrganizationUpdateCode;
  primary_email?: OrganizationUpdatePrimaryEmail;
  primary_phone?: OrganizationUpdatePrimaryPhone;
  subscription_tier?: OrganizationUpdateSubscriptionTier;
}
