/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response for previewing uploaded file data before processing.
 */
export interface PreviewResponse {
  /** First N rows of data for preview */
  data: unknown[][];
  /** Column headers detected */
  columns: string[];
  /** Number of rows included in this preview */
  preview_rows: number;
  /** Total rows in the file */
  total_rows: number;
  /** Total columns in the file */
  total_columns: number;
  /** Name of the uploaded file */
  filename: string;
  /** Current status of the raw import */
  status: string;
}
