/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { ProductionLineSettingsShiftPattern } from './productionLineSettingsShiftPattern';
import type { ProductionLineSettingsNonWorkingDays } from './productionLineSettingsNonWorkingDays';

/**
 * Settings specific to a production line.
Can be inherited from Factory defaults or overridden.
 */
export interface ProductionLineSettings {
  /** If false, uses factory defaults */
  is_custom_schedule?: boolean;
  shift_pattern?: ProductionLineSettingsShiftPattern;
  non_working_days?: ProductionLineSettingsNonWorkingDays;
  [key: string]: unknown;
 }
