/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { ProductionLineReadCode } from './productionLineReadCode';
import type { ProductionLineReadSpecialty } from './productionLineReadSpecialty';
import type { ProductionLineReadTargetOperators } from './productionLineReadTargetOperators';
import type { ProductionLineReadTargetEfficiencyPct } from './productionLineReadTargetEfficiencyPct';
import type { ProductionLineReadSupervisorId } from './productionLineReadSupervisorId';
import type { ProductionLineReadSettings } from './productionLineReadSettings';

/**
 * Schema for reading a production line.
 */
export interface ProductionLineRead {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  code?: ProductionLineReadCode;
  specialty?: ProductionLineReadSpecialty;
  target_operators?: ProductionLineReadTargetOperators;
  target_efficiency_pct?: ProductionLineReadTargetEfficiencyPct;
  id: string;
  factory_id: string;
  supervisor_id?: ProductionLineReadSupervisorId;
  settings?: ProductionLineReadSettings;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
