/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { ProductionDataPoint } from './productionDataPoint';
import type { ProductionChartDataLineFilter } from './productionChartDataLineFilter';

/**
 * Production vs target chart data.
 */
export interface ProductionChartData {
  /** List of daily production metrics for the chart */
  data_points: ProductionDataPoint[];
  /** Active line filter ID, if any */
  line_filter?: ProductionChartDataLineFilter;
}
