/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { ProductionLineUpdateName } from './productionLineUpdateName';
import type { ProductionLineUpdateSpecialty } from './productionLineUpdateSpecialty';
import type { ProductionLineUpdateTargetOperators } from './productionLineUpdateTargetOperators';
import type { ProductionLineUpdateTargetEfficiencyPct } from './productionLineUpdateTargetEfficiencyPct';
import type { ProductionLineUpdateIsActive } from './productionLineUpdateIsActive';
import type { ProductionLineUpdateSettings } from './productionLineUpdateSettings';

/**
 * Schema for updating a production line.
 */
export interface ProductionLineUpdate {
  name?: ProductionLineUpdateName;
  specialty?: ProductionLineUpdateSpecialty;
  target_operators?: ProductionLineUpdateTargetOperators;
  target_efficiency_pct?: ProductionLineUpdateTargetEfficiencyPct;
  is_active?: ProductionLineUpdateIsActive;
  settings?: ProductionLineUpdateSettings;
}
