/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { ProductionLineCreateCode } from './productionLineCreateCode';
import type { ProductionLineCreateSpecialty } from './productionLineCreateSpecialty';
import type { ProductionLineCreateTargetOperators } from './productionLineCreateTargetOperators';
import type { ProductionLineCreateTargetEfficiencyPct } from './productionLineCreateTargetEfficiencyPct';
import type { ProductionLineCreateSettings } from './productionLineCreateSettings';

/**
 * Schema for creating a production line.
 */
export interface ProductionLineCreate {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  code?: ProductionLineCreateCode;
  specialty?: ProductionLineCreateSpecialty;
  target_operators?: ProductionLineCreateTargetOperators;
  target_efficiency_pct?: ProductionLineCreateTargetEfficiencyPct;
  settings?: ProductionLineCreateSettings;
}
