/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { ProductionRunUpdateActualQty } from './productionRunUpdateActualQty';
import type { ProductionRunUpdateWorkedMinutes } from './productionRunUpdateWorkedMinutes';
import type { ProductionRunUpdateOperatorsPresent } from './productionRunUpdateOperatorsPresent';
import type { ProductionRunUpdateSam } from './productionRunUpdateSam';
import type { ProductionRunUpdateWipEnd } from './productionRunUpdateWipEnd';

export interface ProductionRunUpdate {
  actual_qty?: ProductionRunUpdateActualQty;
  worked_minutes?: ProductionRunUpdateWorkedMinutes;
  operators_present?: ProductionRunUpdateOperatorsPresent;
  sam?: ProductionRunUpdateSam;
  wip_end?: ProductionRunUpdateWipEnd;
}
