/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Single point in production chart.
 */
export interface ProductionDataPoint {
  /** Day label (e.g., 'Mon', '2025-12-25') */
  day: string;
  /** Actual units produced on this day */
  actual: number;
  /** Planned/target units for this day */
  target: number;
}
