/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Registration request payload.
 */
export interface RegisterRequest {
  email: string;
  /** @minLength 8 */
  password: string;
  /**
   * @minLength 2
   * @maxLength 255
   */
  full_name: string;
  /**
   * @minLength 2
   * @maxLength 255
   */
  organization_name: string;
  /**
   * @minLength 2
   * @maxLength 50
   */
  organization_code: string;
}
