/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { SamBreakdownItem } from './samBreakdownItem';

/**
 * SAM performance metrics.
 */
export interface SamPerformanceResponse {
  /**
   * Current efficiency percentage based on SAM
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   */
  efficiency: string;
  /**
   * Change in efficiency vs equivalent previous period
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   */
  efficiency_change: string;
  /**
   * Average SAM earned per hour
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   */
  avg_sam_per_hour: string;
  /**
   * Total SAM accumulation
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   */
  total_sam: string;
  /** Breakdown by style for charts */
  breakdown?: SamBreakdownItem[];
}
