/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { SchemaMappingCreateColumnMap } from './schemaMappingCreateColumnMap';
import type { SchemaMappingCreateExtractionRules } from './schemaMappingCreateExtractionRules';
import type { SchemaMappingCreateUserNotes } from './schemaMappingCreateUserNotes';

export interface SchemaMappingCreate {
  /** Mapping from Excel columns to internal fields */
  column_map: SchemaMappingCreateColumnMap;
  /** Parsing rules (skip_rows, header_row, etc.) */
  extraction_rules?: SchemaMappingCreateExtractionRules;
  /** Whether user has validated this mapping */
  reviewed_by_user?: boolean;
  user_notes?: SchemaMappingCreateUserNotes;
}
