/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { SchemaMappingResponseColumnMap } from './schemaMappingResponseColumnMap';
import type { SchemaMappingResponseExtractionRules } from './schemaMappingResponseExtractionRules';
import type { SchemaMappingResponseUserNotes } from './schemaMappingResponseUserNotes';

export interface SchemaMappingResponse {
  id: string;
  version: number;
  is_active: boolean;
  column_map: SchemaMappingResponseColumnMap;
  extraction_rules: SchemaMappingResponseExtractionRules;
  reviewed_by_user: boolean;
  user_notes: SchemaMappingResponseUserNotes;
  created_at: string;
}
