/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { ScopeReadOrganizationId } from './scopeReadOrganizationId';
import type { ScopeReadFactoryId } from './scopeReadFactoryId';
import type { ScopeReadProductionLineId } from './scopeReadProductionLineId';

/**
 * Response schema for a user scope assignment.
 */
export interface ScopeRead {
  id: string;
  scope_type: string;
  organization_id?: ScopeReadOrganizationId;
  factory_id?: ScopeReadFactoryId;
  production_line_id?: ScopeReadProductionLineId;
  role: string;
}
