/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Single point for Speed vs Quality chart.
 */
export interface SpeedQualityPoint {
  /** Date label (e.g., '2025-01-01') */
  date: string;
  /**
   * Average efficiency percentage for this day
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   */
  efficiency_pct: string;
  /**
   * Defects per hundred units (DHU)
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   */
  defects_per_hundred: string;
}
