/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { StyleCreateStyleName } from './styleCreateStyleName';
import type { StyleCreateDescription } from './styleCreateDescription';
import type { StyleCreateBuyer } from './styleCreateBuyer';
import type { StyleCreateSeason } from './styleCreateSeason';
import type { StyleCreateCategory } from './styleCreateCategory';
import type { StyleCreateBaseSam } from './styleCreateBaseSam';
import type { StyleCreateComplexityRating } from './styleCreateComplexityRating';
import type { StyleCreateBomSummary } from './styleCreateBomSummary';
import type { StyleCreateTechPackUrl } from './styleCreateTechPackUrl';

export interface StyleCreate {
  /**
   * Unique identifier for the style (e.g., 'ABC-123', 'POLO-001')
   * @minLength 1
   * @maxLength 100
   */
  style_number: string;
  /** Human-readable name (e.g., 'Classic Polo Shirt') */
  style_name?: StyleCreateStyleName;
  /** Detailed description of the garment */
  description?: StyleCreateDescription;
  /** Brand/customer name (e.g., 'Nike', 'H&M') */
  buyer?: StyleCreateBuyer;
  /** Season code (e.g., 'SS24', 'FW25', 'AW2024') */
  season?: StyleCreateSeason;
  /** Garment category (e.g., 'Tops', 'Bottoms', 'Outerwear') */
  category?: StyleCreateCategory;
  /** Standard Allowed Minute - time to produce one unit (e.g., 12.5 minutes) */
  base_sam?: StyleCreateBaseSam;
  /** Complexity level affecting SAM adjustments */
  complexity_rating?: StyleCreateComplexityRating;
  /** Bill of Materials summary (fabric, trims, accessories) */
  bom_summary?: StyleCreateBomSummary;
  /** URL to technical specification document */
  tech_pack_url?: StyleCreateTechPackUrl;
  factory_id: string;
}
