/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { StyleReadStyleName } from './styleReadStyleName';
import type { StyleReadDescription } from './styleReadDescription';
import type { StyleReadBuyer } from './styleReadBuyer';
import type { StyleReadSeason } from './styleReadSeason';
import type { StyleReadCategory } from './styleReadCategory';
import type { StyleReadBaseSam } from './styleReadBaseSam';
import type { StyleReadComplexityRating } from './styleReadComplexityRating';
import type { StyleReadBomSummary } from './styleReadBomSummary';
import type { StyleReadTechPackUrl } from './styleReadTechPackUrl';

export interface StyleRead {
  /**
   * Unique identifier for the style (e.g., 'ABC-123', 'POLO-001')
   * @minLength 1
   * @maxLength 100
   */
  style_number: string;
  /** Human-readable name (e.g., 'Classic Polo Shirt') */
  style_name?: StyleReadStyleName;
  /** Detailed description of the garment */
  description?: StyleReadDescription;
  /** Brand/customer name (e.g., 'Nike', 'H&M') */
  buyer?: StyleReadBuyer;
  /** Season code (e.g., 'SS24', 'FW25', 'AW2024') */
  season?: StyleReadSeason;
  /** Garment category (e.g., 'Tops', 'Bottoms', 'Outerwear') */
  category?: StyleReadCategory;
  /** Standard Allowed Minute - time to produce one unit (e.g., 12.5 minutes) */
  base_sam?: StyleReadBaseSam;
  /** Complexity level affecting SAM adjustments */
  complexity_rating?: StyleReadComplexityRating;
  /** Bill of Materials summary (fabric, trims, accessories) */
  bom_summary?: StyleReadBomSummary;
  /** URL to technical specification document */
  tech_pack_url?: StyleReadTechPackUrl;
  id: string;
  factory_id: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
