/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Progress of a single style in production.
 */
export interface StyleProgressItem {
  /** Style code (e.g., 'ST-2025-A') */
  style_code: string;
  /** Target production quantity */
  target: number;
  /** Actual production quantity so far */
  actual: number;
  /**
   * Percentage of target completed
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   */
  progress_pct: string;
  /** Status string: 'On Track', 'Behind', 'Completed' */
  status: string;
}
