/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { StyleCreateBomSummaryAnyOf } from './styleCreateBomSummaryAnyOf';

/**
 * Bill of Materials summary (fabric, trims, accessories)
 */
export type StyleCreateBomSummary = StyleCreateBomSummaryAnyOf | null;
