/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Organization subscription tiers.
 */
export type SubscriptionTier = typeof SubscriptionTier[keyof typeof SubscriptionTier];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionTier = {
  starter: 'starter',
  pro: 'pro',
  enterprise: 'enterprise',
} as const;
