/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { UserReadFullName } from './userReadFullName';
import type { UserReadTimezone } from './userReadTimezone';
import type { UserReadPreferences } from './userReadPreferences';
import type { UserReadLastLogin } from './userReadLastLogin';

/**
 * Schema for reading a user.
 */
export interface UserRead {
  email: string;
  full_name?: UserReadFullName;
  id: string;
  organization_id: string;
  role: string;
  is_active: boolean;
  is_verified: boolean;
  timezone?: UserReadTimezone;
  preferences?: UserReadPreferences;
  last_login?: UserReadLastLogin;
  created_at: string;
  updated_at: string;
}
