/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateEmail } from './userUpdateEmail';
import type { UserUpdateFullName } from './userUpdateFullName';
import type { UserUpdateRole } from './userUpdateRole';
import type { UserUpdateTimezone } from './userUpdateTimezone';
import type { UserUpdatePreferences } from './userUpdatePreferences';
import type { UserUpdateIsActive } from './userUpdateIsActive';

/**
 * Schema for updating a user.
 */
export interface UserUpdate {
  email?: UserUpdateEmail;
  full_name?: UserUpdateFullName;
  role?: UserUpdateRole;
  timezone?: UserUpdateTimezone;
  preferences?: UserUpdatePreferences;
  is_active?: UserUpdateIsActive;
}
