/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import type { WidgetConfigWidgetSettings } from './widgetConfigWidgetSettings';

/**
 * Dashboard widget configuration.
 */
export interface WidgetConfig {
  /** List of enabled widget types */
  enabled_widgets?: string[];
  /** Per-widget custom settings */
  widget_settings?: WidgetConfigWidgetSettings;
}
