/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  SampleFile
} from '../../model';

import { customInstance } from '../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List available sample Excel files for testing.
 * @summary List Sample Files
 */
export const listSampleFilesApiV1SamplesSampleFilesGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SampleFile[]>(
      {url: `/api/v1/samples/sample-files`, method: 'GET', signal
    },
      options);
    }
  



export const getListSampleFilesApiV1SamplesSampleFilesGetQueryKey = () => {
    return [
    `/api/v1/samples/sample-files`
    ] as const;
    }

    
export const getListSampleFilesApiV1SamplesSampleFilesGetQueryOptions = <TData = Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSampleFilesApiV1SamplesSampleFilesGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>> = ({ signal }) => listSampleFilesApiV1SamplesSampleFilesGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSampleFilesApiV1SamplesSampleFilesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>>
export type ListSampleFilesApiV1SamplesSampleFilesGetQueryError = unknown


export function useListSampleFilesApiV1SamplesSampleFilesGet<TData = Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>,
          TError,
          Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSampleFilesApiV1SamplesSampleFilesGet<TData = Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>,
          TError,
          Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSampleFilesApiV1SamplesSampleFilesGet<TData = Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Sample Files
 */

export function useListSampleFilesApiV1SamplesSampleFilesGet<TData = Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSampleFilesApiV1SamplesSampleFilesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSampleFilesApiV1SamplesSampleFilesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Download a specific sample file.
 * @summary Download Sample File
 */
export const downloadSampleFileApiV1SamplesSampleFilesFilenameGet = (
    filename: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/samples/sample-files/${filename}`, method: 'GET', signal
    },
      options);
    }
  



export const getDownloadSampleFileApiV1SamplesSampleFilesFilenameGetQueryKey = (filename?: string,) => {
    return [
    `/api/v1/samples/sample-files/${filename}`
    ] as const;
    }

    
export const getDownloadSampleFileApiV1SamplesSampleFilesFilenameGetQueryOptions = <TData = Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>, TError = HTTPValidationError>(filename: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadSampleFileApiV1SamplesSampleFilesFilenameGetQueryKey(filename);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>> = ({ signal }) => downloadSampleFileApiV1SamplesSampleFilesFilenameGet(filename, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(filename), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadSampleFileApiV1SamplesSampleFilesFilenameGetQueryResult = NonNullable<Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>>
export type DownloadSampleFileApiV1SamplesSampleFilesFilenameGetQueryError = HTTPValidationError


export function useDownloadSampleFileApiV1SamplesSampleFilesFilenameGet<TData = Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>, TError = HTTPValidationError>(
 filename: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>,
          TError,
          Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadSampleFileApiV1SamplesSampleFilesFilenameGet<TData = Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>, TError = HTTPValidationError>(
 filename: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>,
          TError,
          Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadSampleFileApiV1SamplesSampleFilesFilenameGet<TData = Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>, TError = HTTPValidationError>(
 filename: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download Sample File
 */

export function useDownloadSampleFileApiV1SamplesSampleFilesFilenameGet<TData = Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>, TError = HTTPValidationError>(
 filename: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadSampleFileApiV1SamplesSampleFilesFilenameGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadSampleFileApiV1SamplesSampleFilesFilenameGetQueryOptions(filename,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



