"""Add style_name to styles

Revision ID: 154aed7cb2f2
Revises: 778a3c455cbf
Create Date: 2025-12-30 17:58:20.294961+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "154aed7cb2f2"
down_revision: str | None = "778a3c455cbf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("uom", sa.String(length=20), nullable=False))
    op.add_column("orders", sa.Column("planned_cut_date", sa.Date(), nullable=True))
    op.add_column("orders", sa.Column("planned_sew_date", sa.Date(), nullable=True))
    op.alter_column(
        "orders",
        "size_breakdown",
        existing_type=mysql.TEXT(),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "orders",
        "status",
        existing_type=mysql.ENUM(
            "PENDING",
            "CONFIRMED",
            "CUTTING",
            "SEWING",
            "FINISHING",
            "PACKING",
            "SHIPPED",
            "CANCELLED",
        ),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "priority",
        existing_type=mysql.ENUM("NORMAL", "RUSH", "CRITICAL"),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.add_column(
        "production_runs",
        sa.Column("factory_id", mysql.CHAR(length=36), nullable=False),
    )
    op.add_column(
        "production_runs", sa.Column("lot_number", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "production_runs", sa.Column("shade_band", sa.String(length=10), nullable=True)
    )
    op.add_column(
        "production_runs",
        sa.Column("sam", sa.Numeric(precision=12, scale=4), nullable=True),
    )
    op.add_column(
        "production_runs",
        sa.Column(
            "efficiency",
            sa.Numeric(precision=10, scale=2),
            sa.Computed(
                "\n            CASE \n                WHEN (worked_minutes * (operators_present + helpers_present)) > 0 AND sam IS NOT NULL\n                THEN ((actual_qty * sam) / (worked_minutes * (operators_present + helpers_present))) * 100 \n                ELSE 0 \n            END\n            ",
            ),
            nullable=True,
        ),
    )
    op.alter_column(
        "production_runs",
        "shift",
        existing_type=mysql.ENUM("DAY", "NIGHT", "OVERTIME"),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "production_runs",
        "operators_present",
        existing_type=mysql.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "production_runs",
        "helpers_present",
        existing_type=mysql.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "production_runs",
        "worked_minutes",
        existing_type=mysql.DECIMAL(precision=12, scale=2),
        type_=sa.Numeric(precision=12, scale=4),
        nullable=False,
    )
    op.alter_column(
        "production_runs",
        "earned_minutes",
        existing_type=mysql.DECIMAL(precision=12, scale=2),
        type_=sa.Numeric(precision=15, scale=4),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_production_runs_factory_id"),
        "production_runs",
        ["factory_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_runs_lot_number"),
        "production_runs",
        ["lot_number"],
        unique=False,
    )
    op.create_foreign_key(
        None, "production_runs", "factories", ["factory_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "styles", sa.Column("style_name", sa.String(length=255), nullable=True)
    )
    op.alter_column(
        "styles",
        "base_sam",
        existing_type=mysql.DECIMAL(precision=10, scale=2),
        type_=sa.Numeric(precision=12, scale=4),
        existing_nullable=True,
    )
    op.alter_column(
        "styles",
        "complexity_rating",
        existing_type=mysql.ENUM("LOW", "MEDIUM", "HIGH"),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "styles",
        "bom_summary",
        existing_type=mysql.TEXT(),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "styles",
        "bom_summary",
        existing_type=sa.JSON(),
        type_=mysql.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "styles",
        "complexity_rating",
        existing_type=sa.String(length=20),
        type_=mysql.ENUM("LOW", "MEDIUM", "HIGH"),
        existing_nullable=True,
    )
    op.alter_column(
        "styles",
        "base_sam",
        existing_type=sa.Numeric(precision=12, scale=4),
        type_=mysql.DECIMAL(precision=10, scale=2),
        existing_nullable=True,
    )
    op.drop_column("styles", "style_name")
    op.drop_constraint(None, "production_runs", type_="foreignkey")
    op.drop_index(op.f("ix_production_runs_lot_number"), table_name="production_runs")
    op.drop_index(op.f("ix_production_runs_factory_id"), table_name="production_runs")
    op.alter_column(
        "production_runs",
        "earned_minutes",
        existing_type=sa.Numeric(precision=15, scale=4),
        type_=mysql.DECIMAL(precision=12, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "production_runs",
        "worked_minutes",
        existing_type=sa.Numeric(precision=12, scale=4),
        type_=mysql.DECIMAL(precision=12, scale=2),
        nullable=True,
    )
    op.alter_column(
        "production_runs",
        "helpers_present",
        existing_type=mysql.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "production_runs",
        "operators_present",
        existing_type=mysql.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "production_runs",
        "shift",
        existing_type=sa.String(length=20),
        type_=mysql.ENUM("DAY", "NIGHT", "OVERTIME"),
        existing_nullable=False,
    )
    op.drop_column("production_runs", "efficiency")
    op.drop_column("production_runs", "sam")
    op.drop_column("production_runs", "shade_band")
    op.drop_column("production_runs", "lot_number")
    op.drop_column("production_runs", "factory_id")
    op.alter_column(
        "orders",
        "priority",
        existing_type=sa.String(length=20),
        type_=mysql.ENUM("NORMAL", "RUSH", "CRITICAL"),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "status",
        existing_type=sa.String(length=20),
        type_=mysql.ENUM(
            "PENDING",
            "CONFIRMED",
            "CUTTING",
            "SEWING",
            "FINISHING",
            "PACKING",
            "SHIPPED",
            "CANCELLED",
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "size_breakdown",
        existing_type=sa.JSON(),
        type_=mysql.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("orders", "planned_sew_date")
    op.drop_column("orders", "planned_cut_date")
    op.drop_column("orders", "uom")
    # ### end Alembic commands ###
