"""Convert Text to JSON for SchemaMapping fields

Revision ID: a412ef5ce347
Revises: 7f5eba0cf1c5
Create Date: 2025-12-29 03:09:20.857474+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a412ef5ce347"
down_revision: str | None = "7f5eba0cf1c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schema_mappings",
        "column_map",
        existing_type=mysql.TEXT(),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "schema_mappings",
        "extraction_rules",
        existing_type=mysql.TEXT(),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "schema_mappings",
        "tier_breakdown",
        existing_type=mysql.TEXT(),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "schema_mappings",
        "fuzzy_scores",
        existing_type=mysql.TEXT(),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "schema_mappings",
        "correction_history",
        existing_type=mysql.TEXT(),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schema_mappings",
        "correction_history",
        existing_type=sa.JSON(),
        type_=mysql.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "schema_mappings",
        "fuzzy_scores",
        existing_type=sa.JSON(),
        type_=mysql.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "schema_mappings",
        "tier_breakdown",
        existing_type=sa.JSON(),
        type_=mysql.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "schema_mappings",
        "extraction_rules",
        existing_type=sa.JSON(),
        type_=mysql.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "schema_mappings",
        "column_map",
        existing_type=sa.JSON(),
        type_=mysql.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
