"""add_production_line_id_to_raw_imports

Revision ID: 8e45e44027df
Revises: 166ae1405eb6
Create Date: 2025-12-27 17:37:56.596677+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
"""add_production_line_id_to_raw_imports

Revision ID: 8e45e44027df
Revises: 166ae1405eb6
Create Date: 2025-12-27 17:37:56.596677+00:00

"""


# revision identifiers, used by Alembic.
revision: str = "8e45e44027df"
down_revision: str | None = "166ae1405eb6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "raw_imports",
        sa.Column("production_line_id", mysql.CHAR(length=36), nullable=True),
    )
    op.create_index(
        op.f("ix_raw_imports_production_line_id"),
        "raw_imports",
        ["production_line_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "raw_imports",
        "production_lines",
        ["production_line_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "raw_imports", type_="foreignkey")
    op.drop_index(op.f("ix_raw_imports_production_line_id"), table_name="raw_imports")
    op.drop_column("raw_imports", "production_line_id")
    # ### end Alembic commands ###
