"""add_inspection_date_make_production_date_nullable

Revision ID: 778a3c455cbf
Revises: 126f40482a68
Create Date: 2025-12-29 09:38:44.600131+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "778a3c455cbf"
down_revision: str | None = "126f40482a68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "production_runs", sa.Column("inspection_date", sa.Date(), nullable=True)
    )
    op.alter_column(
        "production_runs", "production_date", existing_type=sa.DATE(), nullable=True
    )
    op.create_index(
        op.f("ix_production_runs_inspection_date"),
        "production_runs",
        ["inspection_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_production_runs_inspection_date"), table_name="production_runs"
    )
    op.alter_column(
        "production_runs", "production_date", existing_type=sa.DATE(), nullable=False
    )
    op.drop_column("production_runs", "inspection_date")
    # ### end Alembic commands ###
