"""Make time_column nullable in DataSource

Revision ID: 7f5eba0cf1c5
Revises: 57725810a165
Create Date: 2025-12-29 02:56:44.475650+00:00

"""

from collections.abc import Sequence

from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f5eba0cf1c5"
down_revision: str | None = "57725810a165"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "data_sources",
        "time_column",
        existing_type=mysql.VARCHAR(length=100),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "data_sources",
        "time_column",
        existing_type=mysql.VARCHAR(length=100),
        nullable=False,
    )
    # ### end Alembic commands ###
