"""add_batch_and_downtime_to_production_run

Revision ID: 126f40482a68
Revises: a412ef5ce347
Create Date: 2025-12-29 09:32:54.678127+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "126f40482a68"
down_revision: str | None = "a412ef5ce347"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "production_runs",
        sa.Column("batch_number", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "production_runs", sa.Column("downtime_minutes", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_runs",
        sa.Column("downtime_reason", sa.String(length=255), nullable=True),
    )
    op.create_index(
        op.f("ix_production_runs_batch_number"),
        "production_runs",
        ["batch_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_production_runs_batch_number"), table_name="production_runs")
    op.drop_column("production_runs", "downtime_reason")
    op.drop_column("production_runs", "downtime_minutes")
    op.drop_column("production_runs", "batch_number")
    # ### end Alembic commands ###
