"""remove legacy models

Revision ID: 57725810a165
Revises: 2024122817_time_col
Create Date: 2025-12-28 22:50:18.564787+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57725810a165"
down_revision: str | None = "2024122817_time_col"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # op.drop_table('parsed_datasets')

    # op.drop_table('processing_jobs')

    # op.drop_table('excel_uploads')
    op.drop_constraint(op.f("ai_decisions_ibfk_1"), "ai_decisions", type_="foreignkey")
    op.alter_column(
        "ai_decisions",
        "data_source_id",
        existing_type=mysql.CHAR(length=36),
        type_=sa.String(length=36),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_ai_decisions_created_at"), table_name="ai_decisions")
    op.create_foreign_key(
        None, "ai_decisions", "data_sources", ["data_source_id"], ["id"]
    )
    op.drop_column("ai_decisions", "metadata")
    op.alter_column(
        "dashboards",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "dashboards",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "organizations",
        "max_factories",
        existing_type=mysql.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "organizations",
        "max_lines_per_factory",
        existing_type=mysql.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "schema_mappings",
        "user_corrected",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schema_mappings",
        "user_corrected",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'0'"),
        nullable=True,
    )
    op.alter_column(
        "organizations",
        "max_lines_per_factory",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'1'"),
        existing_nullable=False,
    )
    op.alter_column(
        "organizations",
        "max_factories",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'1'"),
        existing_nullable=False,
    )
    op.alter_column(
        "dashboards",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "dashboards",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.add_column("ai_decisions", sa.Column("metadata", mysql.JSON(), nullable=True))
    op.drop_constraint(None, "ai_decisions", type_="foreignkey")
    op.create_foreign_key(
        op.f("ai_decisions_ibfk_1"),
        "ai_decisions",
        "data_sources",
        ["data_source_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_ai_decisions_created_at"), "ai_decisions", ["created_at"], unique=False
    )
    op.alter_column(
        "ai_decisions",
        "data_source_id",
        existing_type=sa.String(length=36),
        type_=mysql.CHAR(length=36),
        existing_nullable=True,
    )
    op.create_table(
        "excel_uploads",
        sa.Column("user_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("factory_id", mysql.CHAR(length=36), nullable=False),
        sa.Column(
            "file_type",
            mysql.ENUM(
                "CRITICAL_PATH",
                "CUTTING_TICKET",
                "PACKING_LIST",
                "PRODUCTION_LOG",
                "QUALITY_REPORT",
                "FABRIC_INVENTORY",
                "WORKER_ROSTER",
                "OTHER",
            ),
            nullable=False,
        ),
        sa.Column("original_filename", mysql.VARCHAR(length=500), nullable=False),
        sa.Column("storage_path", mysql.VARCHAR(length=1000), nullable=False),
        sa.Column(
            "file_size_bytes", mysql.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("mime_type", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("sheet_count", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("row_count", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("column_count", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            mysql.ENUM("PENDING", "VALIDATING", "PROCESSING", "COMPLETED", "FAILED"),
            nullable=False,
        ),
        sa.Column("error_message", mysql.TEXT(), nullable=True),
        sa.Column("uploaded_at", mysql.DATETIME(), nullable=False),
        sa.Column("processed_at", mysql.DATETIME(), nullable=True),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["factory_id"],
            ["factories.id"],
            name="excel_uploads_ibfk_1",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="excel_uploads_ibfk_2", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_excel_uploads_user_id"), "excel_uploads", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_excel_uploads_factory_id"),
        "excel_uploads",
        ["factory_id"],
        unique=False,
    )
    op.create_table(
        "processing_jobs",
        sa.Column("upload_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("llm_model", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("llm_temperature", mysql.VARCHAR(length=10), nullable=True),
        sa.Column(
            "sample_rows_sent", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("schema_inference", mysql.TEXT(), nullable=True),
        sa.Column("inferred_headers", mysql.TEXT(), nullable=True),
        sa.Column("generated_code", mysql.TEXT(), nullable=True),
        sa.Column("code_version", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("execution_log", mysql.TEXT(), nullable=True),
        sa.Column(
            "rows_processed", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("rows_failed", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("tokens_input", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("tokens_output", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            mysql.ENUM(
                "QUEUED",
                "INFERRING",
                "GENERATING",
                "EXECUTING",
                "REVIEWING",
                "COMPLETED",
                "FAILED",
            ),
            nullable=False,
        ),
        sa.Column("error_message", mysql.TEXT(), nullable=True),
        sa.Column("retry_count", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("started_at", mysql.DATETIME(), nullable=True),
        sa.Column("completed_at", mysql.DATETIME(), nullable=True),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["excel_uploads.id"],
            name=op.f("processing_jobs_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_processing_jobs_upload_id"),
        "processing_jobs",
        ["upload_id"],
        unique=False,
    )
    op.create_table(
        "parsed_datasets",
        sa.Column("upload_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("target_table", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("schema_version", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("record_count", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "duplicate_count", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("error_count", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("completeness_pct", mysql.VARCHAR(length=10), nullable=True),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["excel_uploads.id"],
            name=op.f("parsed_datasets_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_parsed_datasets_upload_id"),
        "parsed_datasets",
        ["upload_id"],
        unique=False,
    )
    # ### end Alembic commands ###
