"""add settings to factory

Revision ID: c801b99cd50e
Revises: ea4b6a998c23
Create Date: 2026-01-02 19:56:33.814622+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c801b99cd50e"
down_revision: str | None = "ea4b6a998c23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("factories", sa.Column("settings", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("factories", "settings")
    # ### end Alembic commands ###
