"""add_locale_to_factories

Revision ID: aec8f57a9384
Revises: 8fa9618f3057
Create Date: 2026-01-06 05:29:08.929864+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec8f57a9384'
down_revision: Union[str, None] = '8fa9618f3057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factories', sa.Column('locale', sa.String(length=20), nullable=False, server_default='en-US'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factories', 'locale')
    # ### end Alembic commands ###
