"""drop_zombie_tables_cutting_shipping_compliance

Revision ID: 8fa9618f3057
Revises: 7c986a4f7e3a
Create Date: 2026-01-06 04:16:34.349107+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8fa9618f3057'
down_revision: Union[str, None] = '7c986a4f7e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # 1. Disable Foreign Key Checks
    op.execute("SET FOREIGN_KEY_CHECKS = 0")

    # 2. Drop the blocking Foreign Key (Fail silently if already gone)
    try:
        op.drop_constraint('production_runs_ibfk_1', 'production_runs', type_='foreignkey')
    except Exception:
        pass

    # 3. Drop Tables using SQL "IF EXISTS" to prevent crashes on re-runs
    op.execute("DROP TABLE IF EXISTS cut_tickets")
    op.execute("DROP TABLE IF EXISTS cartons")
    op.execute("DROP TABLE IF EXISTS packing_lists")
    op.execute("DROP TABLE IF EXISTS fabric_lots")
    op.execute("DROP TABLE IF EXISTS traceability_records")

    # 4. Drop the orphan column (Fail silently if already gone)
    try:
        op.drop_column('production_runs', 'cut_ticket_id')
    except Exception:
        pass

    # 5. Handle the Enum change (Update production_events)
    # We wrap this to ensure it doesn't crash if already applied
    try:
        op.alter_column('production_events', 'event_type',
                existing_type=mysql.VARCHAR(length=50),
                type_=sa.Enum('SCAN', 'BATCH_UPLOAD', 'MANUAL_ADJUSTMENT', 'IOT_SIGNAL', name='eventtype', native_enum=False),
                existing_nullable=False)
    except Exception:
        pass

    # 6. Re-enable Foreign Key Checks
    op.execute("SET FOREIGN_KEY_CHECKS = 1")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_runs', sa.Column('cut_ticket_id', mysql.CHAR(length=36), nullable=True))
    op.create_foreign_key('production_runs_ibfk_1', 'production_runs', 'cut_tickets', ['cut_ticket_id'], ['id'], ondelete='SET NULL')
    
    op.alter_column('production_events', 'event_type',
               existing_type=sa.Enum('SCAN', 'BATCH_UPLOAD', 'MANUAL_ADJUSTMENT', 'IOT_SIGNAL', name='eventtype', native_enum=False),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
               
    op.create_table('traceability_records',
    sa.Column('carton_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('fabric_lot_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('cut_ticket_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('production_run_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('compliance_standard', mysql.ENUM('UFLPA', 'EU_DPP', 'CA_SB657', 'UK_MSA', 'OTHER'), nullable=False),
    sa.Column('chain_of_custody', mysql.TEXT(), nullable=True),
    sa.Column('supporting_documents', mysql.TEXT(), nullable=True),
    sa.Column('verification_status', mysql.ENUM('PENDING', 'VERIFIED', 'FLAGGED', 'REJECTED'), nullable=False),
    sa.Column('verified_by_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('verified_at', mysql.DATETIME(), nullable=True),
    sa.Column('risk_score', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('risk_notes', mysql.TEXT(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['carton_id'], ['cartons.id'], name='traceability_records_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cut_ticket_id'], ['cut_tickets.id'], name='traceability_records_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fabric_lot_id'], ['fabric_lots.id'], name='traceability_records_ibfk_3', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['production_run_id'], ['production_runs.id'], name='traceability_records_ibfk_4', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], name='traceability_records_ibfk_5', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    
    op.create_table('fabric_lots',
    sa.Column('factory_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('lot_number', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('fabric_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('composition', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('width_cm', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gsm', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('color', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('supplier', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('origin_country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mill_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('received_date', sa.DATE(), nullable=True),
    sa.Column('initial_meters', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('available_meters', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('reserved_meters', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('unit_cost', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('currency', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('certifications', mysql.TEXT(), nullable=True),
    sa.Column('inspection_status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], name='fabric_lots_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_factory_lot', 'fabric_lots', ['factory_id', 'lot_number'], unique=True)

    op.create_table('packing_lists',
    sa.Column('order_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('packing_list_number', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ship_date', sa.DATE(), nullable=True),
    sa.Column('destination', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ship_to_address', mysql.TEXT(), nullable=True),
    sa.Column('carrier', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tracking_number', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('container_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('total_cartons', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_units', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_net_weight_kg', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_gross_weight_kg', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_cbm', mysql.DECIMAL(precision=8, scale=3), nullable=True),
    sa.Column('status', mysql.ENUM('DRAFT', 'PACKING', 'READY', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED'), nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='packing_lists_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    op.create_table('cartons',
    sa.Column('packing_list_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('carton_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('size_breakdown', mysql.TEXT(), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('total_units', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('net_weight_kg', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('gross_weight_kg', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('dimensions_cm', mysql.TEXT(), nullable=True),
    sa.Column('length_cm', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('width_cm', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height_cm', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('barcode', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['packing_list_id'], ['packing_lists.id'], name='cartons_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    op.create_table('cut_tickets',
    sa.Column('fabric_lot_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('order_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('ticket_number', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('cut_date', sa.DATE(), nullable=True),
    sa.Column('plies', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('marker_length_cm', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('consumption_meters', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('wastage_pct', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('size_ratio', mysql.TEXT(), nullable=True),
    sa.Column('bundle_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_pieces', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cutter_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['cutter_id'], ['workers.id'], name='cut_tickets_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fabric_lot_id'], ['fabric_lots.id'], name='cut_tickets_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='cut_tickets_ibfk_3', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###