"""add settings to production_lines

Revision ID: 8d61fb040358
Revises: c801b99cd50e
Create Date: 2026-01-02 20:27:32.905496+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d61fb040358"
down_revision: str | None = "c801b99cd50e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("production_lines", sa.Column("settings", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("production_lines", "settings")
    # ### end Alembic commands ###
