"""auto_migration

Revision ID: c43214a3c8d0
Revises: a7b9c1d2e3f4
Create Date: 2026-03-05 18:41:17.890231+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c43214a3c8d0'
down_revision: Union[str, None] = 'a7b9c1d2e3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fabric_lots',
    sa.Column('factory_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=False),
    sa.Column('fabric_type', sa.String(length=100), nullable=True),
    sa.Column('composition', sa.String(length=255), nullable=True),
    sa.Column('width_cm', sa.Integer(), nullable=True),
    sa.Column('gsm', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('origin_country', sa.String(length=100), nullable=True),
    sa.Column('mill_name', sa.String(length=255), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('initial_meters', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('available_meters', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reserved_meters', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('inspection_status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'lot_number', name='uq_factory_lot')
    )
    op.create_index(op.f('ix_fabric_lots_factory_id'), 'fabric_lots', ['factory_id'], unique=False)
    op.create_index(op.f('ix_fabric_lots_lot_number'), 'fabric_lots', ['lot_number'], unique=False)
    op.create_index(op.f('ix_fabric_lots_origin_country'), 'fabric_lots', ['origin_country'], unique=False)
    op.create_index(op.f('ix_fabric_lots_supplier'), 'fabric_lots', ['supplier'], unique=False)
    op.create_table('cut_tickets',
    sa.Column('fabric_lot_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('order_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('ticket_number', sa.String(length=100), nullable=False),
    sa.Column('cut_date', sa.Date(), nullable=True),
    sa.Column('plies', sa.Integer(), nullable=True),
    sa.Column('marker_length_cm', sa.Integer(), nullable=True),
    sa.Column('consumption_meters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('wastage_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('size_ratio', sa.Text(), nullable=True),
    sa.Column('bundle_count', sa.Integer(), nullable=True),
    sa.Column('total_pieces', sa.Integer(), nullable=True),
    sa.Column('cutter_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cutter_id'], ['workers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fabric_lot_id'], ['fabric_lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cut_tickets_fabric_lot_id'), 'cut_tickets', ['fabric_lot_id'], unique=False)
    op.create_index(op.f('ix_cut_tickets_order_id'), 'cut_tickets', ['order_id'], unique=False)
    op.create_index(op.f('ix_cut_tickets_ticket_number'), 'cut_tickets', ['ticket_number'], unique=False)
    op.create_table('packing_lists',
    sa.Column('order_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('packing_list_number', sa.String(length=100), nullable=False),
    sa.Column('ship_date', sa.Date(), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('ship_to_address', sa.Text(), nullable=True),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('container_number', sa.String(length=100), nullable=True),
    sa.Column('total_cartons', sa.Integer(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('total_net_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_gross_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cbm', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PACKING', 'READY', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED', name='shipmentstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_lists_order_id'), 'packing_lists', ['order_id'], unique=False)
    op.create_index(op.f('ix_packing_lists_packing_list_number'), 'packing_lists', ['packing_list_number'], unique=False)
    op.create_table('cartons',
    sa.Column('packing_list_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('carton_number', sa.String(length=50), nullable=False),
    sa.Column('size_breakdown', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('net_weight_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('gross_weight_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dimensions_cm', sa.Text(), nullable=True),
    sa.Column('length_cm', sa.Integer(), nullable=True),
    sa.Column('width_cm', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['packing_list_id'], ['packing_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartons_packing_list_id'), 'cartons', ['packing_list_id'], unique=False)
    op.create_table('traceability_records',
    sa.Column('carton_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('fabric_lot_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('cut_ticket_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('production_run_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('compliance_standard', sa.Enum('UFLPA', 'EU_DPP', 'CA_SB657', 'UK_MSA', 'OTHER', name='compliancestandard'), nullable=False),
    sa.Column('chain_of_custody', sa.Text(), nullable=True),
    sa.Column('supporting_documents', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'FLAGGED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('verified_by_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_score', sa.String(length=20), nullable=True),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carton_id'], ['cartons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cut_ticket_id'], ['cut_tickets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fabric_lot_id'], ['fabric_lots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['production_run_id'], ['production_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traceability_records_carton_id'), 'traceability_records', ['carton_id'], unique=False)
    op.create_index(op.f('ix_traceability_records_cut_ticket_id'), 'traceability_records', ['cut_ticket_id'], unique=False)
    op.create_index(op.f('ix_traceability_records_fabric_lot_id'), 'traceability_records', ['fabric_lot_id'], unique=False)
    op.alter_column('data_sources', 'factory_id',
               existing_type=sa.CHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_sources', 'factory_id',
               existing_type=sa.CHAR(length=36),
               nullable=False)
    op.drop_index(op.f('ix_traceability_records_fabric_lot_id'), table_name='traceability_records')
    op.drop_index(op.f('ix_traceability_records_cut_ticket_id'), table_name='traceability_records')
    op.drop_index(op.f('ix_traceability_records_carton_id'), table_name='traceability_records')
    op.drop_table('traceability_records')
    op.drop_index(op.f('ix_cartons_packing_list_id'), table_name='cartons')
    op.drop_table('cartons')
    op.drop_index(op.f('ix_packing_lists_packing_list_number'), table_name='packing_lists')
    op.drop_index(op.f('ix_packing_lists_order_id'), table_name='packing_lists')
    op.drop_table('packing_lists')
    op.drop_index(op.f('ix_cut_tickets_ticket_number'), table_name='cut_tickets')
    op.drop_index(op.f('ix_cut_tickets_order_id'), table_name='cut_tickets')
    op.drop_index(op.f('ix_cut_tickets_fabric_lot_id'), table_name='cut_tickets')
    op.drop_table('cut_tickets')
    op.drop_index(op.f('ix_fabric_lots_supplier'), table_name='fabric_lots')
    op.drop_index(op.f('ix_fabric_lots_origin_country'), table_name='fabric_lots')
    op.drop_index(op.f('ix_fabric_lots_lot_number'), table_name='fabric_lots')
    op.drop_index(op.f('ix_fabric_lots_factory_id'), table_name='fabric_lots')
    op.drop_table('fabric_lots')
    # ### end Alembic commands ###
