# Copyright (c) 2026 Aaron Guo. All rights reserved.
# Use of this source code is governed by the proprietary license
# found in the LICENSE file in the root directory of this source tree.

"""auto_migration

Revision ID: 1074e983edde
Revises: b3acb5af48a7
Create Date: 2026-01-17 07:25:36.613241+00:00

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1074e983edde'
down_revision: str | None = 'b3acb5af48a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_production_run', 'production_runs', ['data_source_id', 'order_id', 'production_date', 'shift'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_production_run', 'production_runs', type_='unique')
    # ### end Alembic commands ###
