"""auto_migration

Revision ID: 1074e983edde
Revises: b3acb5af48a7
Create Date: 2026-01-17 07:25:36.613241+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1074e983edde'
down_revision: Union[str, None] = 'b3acb5af48a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_production_run', 'production_runs', ['data_source_id', 'order_id', 'production_date', 'shift'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_production_run', 'production_runs', type_='unique')
    # ### end Alembic commands ###
