"""fix_user_role_enum

Revision ID: e4a3e6875704
Revises: 7684e329d9fc
Create Date: 2026-01-08 08:15:10.074097+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a3e6875704'
down_revision: Union[str, None] = '7684e329d9fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual Fix: Update UserRole Enum in 3 steps to handle existing data safely
    
    # 1. Temporarily relax to VARCHAR to allow any string
    op.execute("ALTER TABLE users MODIFY COLUMN role VARCHAR(50)")
    
    # 2. Migrate existing 'MANAGER' data to 'factory_manager' (defaulting to factory manager)
    op.execute("UPDATE users SET role = 'factory_manager' WHERE role = 'MANAGER'")
    
    # 3. Apply new ENUM definition
    op.execute("ALTER TABLE users MODIFY COLUMN role ENUM('system_admin', 'owner', 'factory_manager', 'line_manager', 'analyst', 'viewer') NOT NULL")

    # Commented out potentially dangerous auto-gen FKs
    # op.create_foreign_key('fk_dashboard_user', 'dashboards', 'users', ['user_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # op.create_foreign_key('fk_dashboard_datasource', 'dashboards', 'data_sources', ['data_source_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # op.create_foreign_key('fk_factory_org', 'factories', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # op.create_foreign_key(None, 'production_lines', 'workers', ['supervisor_id'], ['id'], ondelete='SET NULL')
    # op.create_foreign_key('fk_line_factory', 'production_lines', 'factories', ['factory_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_line_factory', 'production_lines', type_='foreignkey')
    op.drop_constraint(None, 'production_lines', type_='foreignkey')
    op.drop_constraint('fk_factory_org', 'factories', type_='foreignkey')
    op.drop_constraint('fk_dashboard_datasource', 'dashboards', type_='foreignkey')
    op.drop_constraint('fk_dashboard_user', 'dashboards', type_='foreignkey')
    # ### end Alembic commands ###
