"""add_production_event_model

Revision ID: 7c986a4f7e3a
Revises: e6ba6ace75cb
Create Date: 2026-01-05 00:27:18.601810+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c986a4f7e3a"
down_revision: str | None = "e6ba6ace75cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "production_events",
        sa.Column("production_run_id", mysql.CHAR(length=36), nullable=True),
    )
    op.create_index(
        op.f("ix_production_events_production_run_id"),
        "production_events",
        ["production_run_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "production_events",
        "production_runs",
        ["production_run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "production_runs",
        "source_import_id",
        existing_type=mysql.VARCHAR(length=36),
        type_=mysql.CHAR(length=36),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_production_runs_source_import_id"),
        "production_runs",
        ["source_import_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "production_runs",
        "raw_imports",
        ["source_import_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "production_runs", type_="foreignkey")
    op.drop_index(
        op.f("ix_production_runs_source_import_id"), table_name="production_runs"
    )
    op.alter_column(
        "production_runs",
        "source_import_id",
        existing_type=mysql.CHAR(length=36),
        type_=mysql.VARCHAR(length=36),
        existing_nullable=True,
    )
    op.drop_constraint(None, "production_events", type_="foreignkey")
    op.drop_index(
        op.f("ix_production_events_production_run_id"), table_name="production_events"
    )
    op.drop_column("production_events", "production_run_id")
    # ### end Alembic commands ###
