/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  OrganizationRead,
  OrganizationUpdate
} from '../../model';

import { customInstance } from '../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get the current user's organization.

Returns the organization that the authenticated user belongs to.
 * @summary Get My Organization
 */
export const getMyOrganizationApiV1OrganizationsMeGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OrganizationRead>(
      {url: `/api/v1/organizations/me`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMyOrganizationApiV1OrganizationsMeGetQueryKey = () => {
    return [
    `/api/v1/organizations/me`
    ] as const;
    }

    
export const getGetMyOrganizationApiV1OrganizationsMeGetQueryOptions = <TData = Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyOrganizationApiV1OrganizationsMeGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>> = ({ signal }) => getMyOrganizationApiV1OrganizationsMeGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyOrganizationApiV1OrganizationsMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>>
export type GetMyOrganizationApiV1OrganizationsMeGetQueryError = unknown


export function useGetMyOrganizationApiV1OrganizationsMeGet<TData = Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>,
          TError,
          Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyOrganizationApiV1OrganizationsMeGet<TData = Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>,
          TError,
          Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyOrganizationApiV1OrganizationsMeGet<TData = Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get My Organization
 */

export function useGetMyOrganizationApiV1OrganizationsMeGet<TData = Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyOrganizationApiV1OrganizationsMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyOrganizationApiV1OrganizationsMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update the current user's organization.

Only admins can update organization details.
Updatable fields: name, code, primary_email, primary_phone, subscription_tier
 * @summary Update My Organization
 */
export const updateMyOrganizationApiV1OrganizationsMePatch = (
    organizationUpdate: OrganizationUpdate,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<OrganizationRead>(
      {url: `/api/v1/organizations/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: organizationUpdate
    },
      options);
    }
  


export const getUpdateMyOrganizationApiV1OrganizationsMePatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMyOrganizationApiV1OrganizationsMePatch>>, TError,{data: OrganizationUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMyOrganizationApiV1OrganizationsMePatch>>, TError,{data: OrganizationUpdate}, TContext> => {

const mutationKey = ['updateMyOrganizationApiV1OrganizationsMePatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMyOrganizationApiV1OrganizationsMePatch>>, {data: OrganizationUpdate}> = (props) => {
          const {data} = props ?? {};

          return  updateMyOrganizationApiV1OrganizationsMePatch(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMyOrganizationApiV1OrganizationsMePatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateMyOrganizationApiV1OrganizationsMePatch>>>
    export type UpdateMyOrganizationApiV1OrganizationsMePatchMutationBody = OrganizationUpdate
    export type UpdateMyOrganizationApiV1OrganizationsMePatchMutationError = HTTPValidationError

    /**
 * @summary Update My Organization
 */
export const useUpdateMyOrganizationApiV1OrganizationsMePatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMyOrganizationApiV1OrganizationsMePatch>>, TError,{data: OrganizationUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMyOrganizationApiV1OrganizationsMePatch>>,
        TError,
        {data: OrganizationUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateMyOrganizationApiV1OrganizationsMePatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get organization's quota status.

Returns current usage and limits for factories and production lines.
 * @summary Get Quota Status
 */
export const getQuotaStatusApiV1OrganizationsQuotaStatusGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/organizations/quota-status`, method: 'GET', signal
    },
      options);
    }
  



export const getGetQuotaStatusApiV1OrganizationsQuotaStatusGetQueryKey = () => {
    return [
    `/api/v1/organizations/quota-status`
    ] as const;
    }

    
export const getGetQuotaStatusApiV1OrganizationsQuotaStatusGetQueryOptions = <TData = Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuotaStatusApiV1OrganizationsQuotaStatusGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>> = ({ signal }) => getQuotaStatusApiV1OrganizationsQuotaStatusGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuotaStatusApiV1OrganizationsQuotaStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>>
export type GetQuotaStatusApiV1OrganizationsQuotaStatusGetQueryError = unknown


export function useGetQuotaStatusApiV1OrganizationsQuotaStatusGet<TData = Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuotaStatusApiV1OrganizationsQuotaStatusGet<TData = Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuotaStatusApiV1OrganizationsQuotaStatusGet<TData = Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Quota Status
 */

export function useGetQuotaStatusApiV1OrganizationsQuotaStatusGet<TData = Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuotaStatusApiV1OrganizationsQuotaStatusGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuotaStatusApiV1OrganizationsQuotaStatusGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get a specific organization by ID.

Users can only view their own organization.
 * @summary Get Organization
 */
export const getOrganizationApiV1OrganizationsOrganizationIdGet = (
    organizationId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OrganizationRead>(
      {url: `/api/v1/organizations/${organizationId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetOrganizationApiV1OrganizationsOrganizationIdGetQueryKey = (organizationId?: string,) => {
    return [
    `/api/v1/organizations/${organizationId}`
    ] as const;
    }

    
export const getGetOrganizationApiV1OrganizationsOrganizationIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>, TError = HTTPValidationError>(organizationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrganizationApiV1OrganizationsOrganizationIdGetQueryKey(organizationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>> = ({ signal }) => getOrganizationApiV1OrganizationsOrganizationIdGet(organizationId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrganizationApiV1OrganizationsOrganizationIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>>
export type GetOrganizationApiV1OrganizationsOrganizationIdGetQueryError = HTTPValidationError


export function useGetOrganizationApiV1OrganizationsOrganizationIdGet<TData = Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>, TError = HTTPValidationError>(
 organizationId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>,
          TError,
          Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrganizationApiV1OrganizationsOrganizationIdGet<TData = Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>, TError = HTTPValidationError>(
 organizationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>,
          TError,
          Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrganizationApiV1OrganizationsOrganizationIdGet<TData = Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>, TError = HTTPValidationError>(
 organizationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Organization
 */

export function useGetOrganizationApiV1OrganizationsOrganizationIdGet<TData = Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>, TError = HTTPValidationError>(
 organizationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrganizationIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrganizationApiV1OrganizationsOrganizationIdGetQueryOptions(organizationId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



