/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  OrganizationRead
} from '../../model';


export const getGetMyOrganizationApiV1OrganizationsMeGetResponseMock = (overrideResponse: Partial< OrganizationRead > = {}): OrganizationRead => ({name: faker.string.alpha({length: {min: 1, max: 255}}), code: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 50}}),null,]), undefined]), primary_email: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.email(),null,]), undefined]), primary_phone: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 50}}),null,]), undefined]), id: faker.string.alpha({length: {min: 10, max: 20}}), subscription_tier: faker.string.alpha({length: {min: 10, max: 20}}), created_at: `${faker.date.past().toISOString().split('.')[0]}Z`, updated_at: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getUpdateMyOrganizationApiV1OrganizationsMePatchResponseMock = (overrideResponse: Partial< OrganizationRead > = {}): OrganizationRead => ({name: faker.string.alpha({length: {min: 1, max: 255}}), code: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 50}}),null,]), undefined]), primary_email: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.email(),null,]), undefined]), primary_phone: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 50}}),null,]), undefined]), id: faker.string.alpha({length: {min: 10, max: 20}}), subscription_tier: faker.string.alpha({length: {min: 10, max: 20}}), created_at: `${faker.date.past().toISOString().split('.')[0]}Z`, updated_at: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getGetOrganizationApiV1OrganizationsOrganizationIdGetResponseMock = (overrideResponse: Partial< OrganizationRead > = {}): OrganizationRead => ({name: faker.string.alpha({length: {min: 1, max: 255}}), code: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 50}}),null,]), undefined]), primary_email: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.email(),null,]), undefined]), primary_phone: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 50}}),null,]), undefined]), id: faker.string.alpha({length: {min: 10, max: 20}}), subscription_tier: faker.string.alpha({length: {min: 10, max: 20}}), created_at: `${faker.date.past().toISOString().split('.')[0]}Z`, updated_at: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})


export const getGetMyOrganizationApiV1OrganizationsMeGetMockHandler = (overrideResponse?: OrganizationRead | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<OrganizationRead> | OrganizationRead), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/organizations/me', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMyOrganizationApiV1OrganizationsMeGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateMyOrganizationApiV1OrganizationsMePatchMockHandler = (overrideResponse?: OrganizationRead | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<OrganizationRead> | OrganizationRead), options?: RequestHandlerOptions) => {
  return http.patch('*/api/v1/organizations/me', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateMyOrganizationApiV1OrganizationsMePatchResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetQuotaStatusApiV1OrganizationsQuotaStatusGetMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<unknown> | unknown), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/organizations/quota-status', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getGetOrganizationApiV1OrganizationsOrganizationIdGetMockHandler = (overrideResponse?: OrganizationRead | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<OrganizationRead> | OrganizationRead), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/organizations/:organizationId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetOrganizationApiV1OrganizationsOrganizationIdGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getOrganizationsMock = () => [
  getGetMyOrganizationApiV1OrganizationsMeGetMockHandler(),
  getUpdateMyOrganizationApiV1OrganizationsMePatchMockHandler(),
  getGetQuotaStatusApiV1OrganizationsQuotaStatusGetMockHandler(),
  getGetOrganizationApiV1OrganizationsOrganizationIdGetMockHandler()
]
