/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  MemberRead,
  ScopeRead
} from '../../model';


export const getListOrganizationMembersApiV1OrganizationsMembersGetResponseMock = (): MemberRead[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.internet.email(), full_name: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), avatar_url: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), role: faker.string.alpha({length: {min: 10, max: 20}}), is_active: faker.datatype.boolean(), last_login: faker.helpers.arrayElement([faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`,null,]), undefined]), scopes: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), scope_type: faker.string.alpha({length: {min: 10, max: 20}}), organization_id: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), factory_id: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), data_source_id: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), role: faker.string.alpha({length: {min: 10, max: 20}})})), undefined])})))

export const getAssignUserToDataSourceApiV1OrganizationsMembersUserIdScopesPostResponseMock = (overrideResponse: Partial< ScopeRead > = {}): ScopeRead => ({id: faker.string.alpha({length: {min: 10, max: 20}}), scope_type: faker.string.alpha({length: {min: 10, max: 20}}), organization_id: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), factory_id: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), data_source_id: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), role: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getListOrganizationMembersApiV1OrganizationsMembersGetMockHandler = (overrideResponse?: MemberRead[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MemberRead[]> | MemberRead[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/organizations/members', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListOrganizationMembersApiV1OrganizationsMembersGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getAssignUserToDataSourceApiV1OrganizationsMembersUserIdScopesPostMockHandler = (overrideResponse?: ScopeRead | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ScopeRead> | ScopeRead), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/organizations/members/:userId/scopes', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAssignUserToDataSourceApiV1OrganizationsMembersUserIdScopesPostResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getRemoveUserScopeApiV1OrganizationsMembersUserIdScopesScopeIdDeleteMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/organizations/members/:userId/scopes/:scopeId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}
export const getTeamManagementMock = () => [
  getListOrganizationMembersApiV1OrganizationsMembersGetMockHandler(),
  getAssignUserToDataSourceApiV1OrganizationsMembersUserIdScopesPostMockHandler(),
  getRemoveUserScopeApiV1OrganizationsMembersUserIdScopesScopeIdDeleteMockHandler()
]
