/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError
} from '../../model';

import { customInstance } from '../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Deprecated: Process File
 */
export const deprecatedProcessFileApiV1UploadsProcessFileIdPost = (
    fileId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/uploads/process/${fileId}`, method: 'POST', signal
    },
      options);
    }
  


export const getDeprecatedProcessFileApiV1UploadsProcessFileIdPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deprecatedProcessFileApiV1UploadsProcessFileIdPost>>, TError,{fileId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deprecatedProcessFileApiV1UploadsProcessFileIdPost>>, TError,{fileId: string}, TContext> => {

const mutationKey = ['deprecatedProcessFileApiV1UploadsProcessFileIdPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deprecatedProcessFileApiV1UploadsProcessFileIdPost>>, {fileId: string}> = (props) => {
          const {fileId} = props ?? {};

          return  deprecatedProcessFileApiV1UploadsProcessFileIdPost(fileId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeprecatedProcessFileApiV1UploadsProcessFileIdPostMutationResult = NonNullable<Awaited<ReturnType<typeof deprecatedProcessFileApiV1UploadsProcessFileIdPost>>>
    
    export type DeprecatedProcessFileApiV1UploadsProcessFileIdPostMutationError = HTTPValidationError

    /**
 * @summary Deprecated: Process File
 */
export const useDeprecatedProcessFileApiV1UploadsProcessFileIdPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deprecatedProcessFileApiV1UploadsProcessFileIdPost>>, TError,{fileId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deprecatedProcessFileApiV1UploadsProcessFileIdPost>>,
        TError,
        {fileId: string},
        TContext
      > => {

      const mutationOptions = getDeprecatedProcessFileApiV1UploadsProcessFileIdPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Deprecated: Get Job Status
 */
export const deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet = (
    jobId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/uploads/process/status/${jobId}`, method: 'GET', signal
    },
      options);
    }
  



export const getDeprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGetQueryKey = (jobId?: string,) => {
    return [
    `/api/v1/uploads/process/status/${jobId}`
    ] as const;
    }

    
export const getDeprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGetQueryOptions = <TData = Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>, TError = HTTPValidationError>(jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGetQueryKey(jobId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>> = ({ signal }) => deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet(jobId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(jobId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>>
export type DeprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGetQueryError = HTTPValidationError


export function useDeprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet<TData = Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>, TError = HTTPValidationError>(
 jobId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>,
          TError,
          Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet<TData = Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>, TError = HTTPValidationError>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>,
          TError,
          Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet<TData = Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>, TError = HTTPValidationError>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Deprecated: Get Job Status
 */

export function useDeprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet<TData = Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>, TError = HTTPValidationError>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeprecatedGetJobStatusApiV1UploadsProcessStatusJobIdGetQueryOptions(jobId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



