/*
 * Copyright (c) 2026 Aaron Guo. All rights reserved.
 * Use of this source code is governed by the proprietary license
 * found in the LICENSE file in the root directory of this source tree.
 */

/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * LineSight
 * LineSight: AI-driven Semantic ETL platform for SMB apparel manufacturing. Parse messy Excel files, track SAM/DHU metrics, and ensure UFLPA compliance.
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  DashboardDetailResponse,
  DashboardListResponse,
  DashboardResponse
} from '../../model';


export const getCreateDashboardApiV1DashboardsPostResponseMock = (overrideResponse: Partial< DashboardResponse > = {}): DashboardResponse => ({id: faker.string.alpha({length: {min: 10, max: 20}}), user_id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), data_source_id: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), widget_config: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), layout_config: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), created_at: `${faker.date.past().toISOString().split('.')[0]}Z`, updated_at: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getListDashboardsApiV1DashboardsGetResponseMock = (overrideResponse: Partial< DashboardListResponse > = {}): DashboardListResponse => ({dashboards: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), user_id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), data_source_id: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), widget_config: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), layout_config: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), created_at: `${faker.date.past().toISOString().split('.')[0]}Z`, updated_at: `${faker.date.past().toISOString().split('.')[0]}Z`})), count: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getGetDashboardApiV1DashboardsDashboardIdGetResponseMock = (overrideResponse: Partial< DashboardDetailResponse > = {}): DashboardDetailResponse => ({id: faker.string.alpha({length: {min: 10, max: 20}}), user_id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), data_source_id: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), widget_config: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), layout_config: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), created_at: `${faker.date.past().toISOString().split('.')[0]}Z`, updated_at: `${faker.date.past().toISOString().split('.')[0]}Z`, widget_data: faker.helpers.arrayElement([faker.helpers.arrayElement([null,]), undefined]), ...overrideResponse})

export const getUpdateDashboardApiV1DashboardsDashboardIdPutResponseMock = (overrideResponse: Partial< DashboardResponse > = {}): DashboardResponse => ({id: faker.string.alpha({length: {min: 10, max: 20}}), user_id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), data_source_id: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), widget_config: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), layout_config: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined]), created_at: `${faker.date.past().toISOString().split('.')[0]}Z`, updated_at: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})


export const getCreateDashboardApiV1DashboardsPostMockHandler = (overrideResponse?: DashboardResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DashboardResponse> | DashboardResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/dashboards/', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateDashboardApiV1DashboardsPostResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getListDashboardsApiV1DashboardsGetMockHandler = (overrideResponse?: DashboardListResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DashboardListResponse> | DashboardListResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/dashboards/', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListDashboardsApiV1DashboardsGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetDashboardApiV1DashboardsDashboardIdGetMockHandler = (overrideResponse?: DashboardDetailResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DashboardDetailResponse> | DashboardDetailResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/dashboards/:dashboardId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDashboardApiV1DashboardsDashboardIdGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateDashboardApiV1DashboardsDashboardIdPutMockHandler = (overrideResponse?: DashboardResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<DashboardResponse> | DashboardResponse), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/dashboards/:dashboardId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateDashboardApiV1DashboardsDashboardIdPutResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteDashboardApiV1DashboardsDashboardIdDeleteMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/dashboards/:dashboardId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}
export const getDashboardsMock = () => [
  getCreateDashboardApiV1DashboardsPostMockHandler(),
  getListDashboardsApiV1DashboardsGetMockHandler(),
  getGetDashboardApiV1DashboardsDashboardIdGetMockHandler(),
  getUpdateDashboardApiV1DashboardsDashboardIdPutMockHandler(),
  getDeleteDashboardApiV1DashboardsDashboardIdDeleteMockHandler()
]
